import { Spot, SuggestedItinerary } from './types'

export const spots: Spot[] = [

  // ══════════════════════════════════════════════════════
  // 你的行程餐廳（Day 2 / 3 / 5）
  // ══════════════════════════════════════════════════════

  {
    id: 'r1',
    slug: 'ribs-of-legend-haeundae',
    name_ko: '리브스 오브 레전드 해운대',
    name_zh: '傳說肋排 海雲台店',
    name_en: 'Ribs of Legend Haeundae',
    type: 'restaurant',
    description: '海雲台海灘旁3樓的高級韓式烤牛名店，以頂級牛肋排聞名，肉質油花豐富。窗邊座位可眺望海雲台海灘夜景，是 Day 2 晚餐首選。',
    address_ko: '부산 해운대구 해운대해변로 277 3층',
    address_zh: '釜山海雲台區海雲台海邊路277號 3樓',
    district: '海雲台',
    city: '釜山',
    lat: 35.1631,
    lng: 129.1604,
    image_url: 'https://images.unsplash.com/photo-1529692236671-f1f6cf9683ba?w=800&q=80',
    price_range: 'expensive',
    avg_price_krw: 60000,
    spice_level: 'none',
    cuisine_type: ['韓式烤肉', '烤牛'],
    kid_friendly_score: 3,
    kid_friendly_notes: '烤肉由店員操作，可為小孩切小塊。環境較安靜高級，小孩若吵鬧可能不方便。',
    has_english_menu: false,
    accepts_card: true,
    reservation_required: true,
    reservation_links: [
      {
        platform: 'Catch Table',
        url: 'https://global.catchtable.co.kr/ct/restaurants/search?keyword=%EB%A6%AC%EB%B8%8C%EC%8A%A4+%EC%98%A4%EB%B8%8C+%EB%A0%88%EC%A0%84%EB%93%9C',
        label: 'Catch Table Global 訂位',
        note: '搜尋「리브스 오브 레전드」找到後直接訂位',
      },
      {
        platform: 'Naver',
        url: 'https://map.naver.com/v5/search/%EB%A6%AC%EB%B8%8C%EC%8A%A4+%EC%98%A4%EB%B8%8C+%EB%A0%88%EC%A0%84%EB%93%9C+%ED%95%B4%EC%9A%B4%EB%8C%80',
        label: 'Naver Map 查看位置',
      },
    ],
    recommended_dishes: [
      { name_ko: '꽃등심', name_zh: '花紋肋眼', price_krw: 65000, description: '招牌！油花均勻，炭火烤出外焦內嫩', must_order: true },
      { name_ko: '갈비살', name_zh: '牛肋排肉', price_krw: 55000, description: '帶骨牛肋肉，口感豐富香氣十足', must_order: true },
    ],
    ordering_tips: [
      '烤肉由店員操作，不需自己烤',
      '海景座位說「바다 보이는 자리 주세요」',
      '小孩的肉請店員剪小塊「작게 잘라주세요」',
    ],
    review_summary: {
      pros: ['海景窗邊座位絕美，適合特別場合', '肉質水準穩定、油花豐富', '店員服務好會主動幫切肉'],
      cons: ['價格偏高，人均約台幣1,500以上', '週末需提前至少一週訂位', '環境較正式，帶小小孩可能有壓力'],
    },
    opening_hours: { mon: '17:00-23:00', tue: '17:00-23:00', wed: '17:00-23:00', thu: '17:00-23:00', fri: '17:00-00:00', sat: '12:00-00:00', sun: '12:00-23:00' },
    tips: ['Day 2（4/2）晚餐，包車回來後前往', '飯後沿海雲台海灘散步消化'],
    tags: ['烤牛', '海景', '高級', 'Day2', '4/2'],
    rating: 4.6,
    review_count: 890,
  },

  {
    id: 'r2',
    slug: 'haejok-ssallong-haeundae',
    name_ko: '해적쌀롱 해운대본점',
    name_zh: '海賊飯廊 海雲台本店',
    name_en: 'Haejok Ssallong Haeundae',
    type: 'restaurant',
    description: '海雲台人氣海鮮餐廳，提供釜山在地新鮮漁獲，炭火燒烤或生食皆有。帝王蟹、鮑魚、海鮮鍋是招牌，是 Day 3 晚餐的絕佳選擇。',
    address_ko: '부산 해운대구 구남로12번길 8 1층, 2층',
    address_zh: '釜山海雲台區九南路12巷8號 1-2樓',
    district: '海雲台',
    city: '釜山',
    lat: 35.1585,
    lng: 129.1602,
    image_url: 'https://images.unsplash.com/photo-1519984388953-d2406bc725e1?w=800&q=80',
    price_range: 'expensive',
    avg_price_krw: 50000,
    spice_level: 'mild',
    cuisine_type: ['海鮮', '活海鮮'],
    kid_friendly_score: 3,
    kid_friendly_notes: '蒸帝王蟹、烤鮑魚都是無辣料理，小孩可吃。帶孩子建議點蒸類而非辣湯鍋。',
    has_english_menu: false,
    accepts_card: true,
    reservation_required: true,
    reservation_links: [
      {
        platform: 'Catch Table',
        url: 'https://global.catchtable.co.kr/ct/restaurants/search?keyword=%ED%95%B4%EC%A0%81%EC%8C%80%EB%A1%B1',
        label: 'Catch Table Global 訂位',
        note: '搜尋「해적쌀롱」找到後直接訂位',
      },
      {
        platform: 'Naver',
        url: 'https://map.naver.com/v5/search/%ED%95%B4%EC%A0%81%EC%8C%80%EB%A1%B1+%ED%95%B4%EC%9A%B4%EB%8C%80%EB%B3%B8%EC%A0%90',
        label: 'Naver Map 查看位置',
      },
    ],
    recommended_dishes: [
      { name_ko: '킹크랩（蒸）', name_zh: '清蒸帝王蟹', price_krw: 150000, description: '活體帝王蟹現點現蒸，鮮甜無辣，小孩可吃', must_order: true },
      { name_ko: '전복구이', name_zh: '烤鮑魚', price_krw: 30000, description: '炭火烤鮑魚加奶油，香氣四溢無辣', must_order: true },
      { name_ko: '해물탕', name_zh: '海鮮鍋', price_krw: 60000, description: '辣湯鍋，成人適合，小孩避開', must_order: false },
    ],
    ordering_tips: [
      '帶小孩建議點「찜（蒸）」而非辣鍋',
      '帝王蟹按市價，點前確認價格「얼마예요?」',
      '白飯加點說「공기밥 주세요」₩2,000',
    ],
    review_summary: {
      pros: ['海鮮品質新鮮，釜山直送', '帝王蟹份量大、值回票價', '空間寬敞，氣氛好'],
      cons: ['帝王蟹為市價，費用不固定可能偏高', '週末需提前訂位', '辣鍋類小孩不適合，要注意點餐'],
    },
    opening_hours: { mon: '12:00-22:00', tue: '12:00-22:00', wed: '12:00-22:00', thu: '12:00-22:00', fri: '12:00-23:00', sat: '11:00-23:00', sun: '11:00-22:00' },
    tips: ['Day 3（4/3）晚餐，包車回來後前往'],
    tags: ['海鮮', '帝王蟹', '海雲台', 'Day3', '4/3'],
    rating: 4.5,
    review_count: 1240,
  },

  {
    id: 'r3',
    slug: 'haemok-michelin-eel',
    name_ko: '해목',
    name_zh: '海木（米其林鰻魚）',
    name_en: 'Haemok',
    type: 'restaurant',
    description: '釜山米其林推薦鰻魚專門店，炭火慢烤鮮活鰻魚，皮脆肉嫩，是整趟旅程最完美的收尾晚餐。',
    address_ko: '부산 해운대구 해운대시장 일대',
    address_zh: '釜山海雲台區海雲台市場一帶',
    district: '海雲台',
    city: '釜山',
    lat: 35.1630,
    lng: 129.1600,
    image_url: 'https://images.unsplash.com/photo-1534482421-64566f976cfa?w=800&q=80',
    price_range: 'expensive',
    avg_price_krw: 55000,
    spice_level: 'none',
    cuisine_type: ['鰻魚', '米其林'],
    kid_friendly_score: 3,
    kid_friendly_notes: '鰻魚本身無辣，小孩可吃。鰻魚飯（장어덮밥）特別適合小孩。需幫小孩去骨。',
    has_english_menu: false,
    accepts_card: true,
    reservation_required: true,
    reservation_links: [
      {
        platform: 'Catch Table',
        url: 'https://global.catchtable.co.kr/ct/shop/Y2F0Y2hfeFFMalYxSWhPTm5PLythNWYwNTB2Zz09',
        label: 'Catch Table Global 訂位',
        note: '米其林名店旺季可能需提前 2 週',
      },
      {
        platform: 'Naver',
        url: 'https://map.naver.com/v5/search/%ED%95%B4%EB%AA%A9+%ED%95%B4%EC%9A%B4%EB%8C%80',
        label: 'Naver Map 查看位置',
      },
      {
        platform: 'Tabling',
        url: 'https://www.tabling.co.kr/restaurant/2124',
        label: 'Tabling 線上候位',
        note: '可遠端加入候位，減少現場等待',
      },
    ],
    recommended_dishes: [
      { name_ko: '장어구이', name_zh: '烤鰻魚', price_krw: 55000, description: '招牌！炭火慢烤，皮脆肉嫩，無辣', must_order: true },
      { name_ko: '장어덮밥', name_zh: '鰻魚飯', price_krw: 22000, description: '蒲燒鰻魚蓋飯，甜醬入飯，小孩最愛', must_order: true },
      { name_ko: '장어탕', name_zh: '鰻魚湯', price_krw: 18000, description: '清湯，暖胃補身，無辣', must_order: false },
    ],
    ordering_tips: [
      '告知幾人用餐，鰻魚按「條」計價',
      '幫小孩點鰻魚飯（장어덮밥）最方便',
      '幫小孩去骨說「뼈 발라주세요」',
    ],
    review_summary: {
      pros: ['米其林水準，鰻魚鮮度與火候俱佳', '師傅在桌邊烤，是一種用餐體驗', '無辣，各年齡都能接受'],
      cons: ['價位偏高，人均約台幣1,200起', '需提前訂位，旺季難訂', '停車不方便'],
    },
    opening_hours: { mon: '11:30-21:30', tue: '11:30-21:30', wed: '11:30-21:30', thu: '11:30-21:30', fri: '11:30-21:30', sat: '11:30-21:30', sun: '11:30-21:30', note: '售完即止' },
    tips: ['Day 5 最後一天壓軸晚餐', '米其林推薦，用最完美的方式結束旅程'],
    tags: ['米其林', '鰻魚', '海雲台', 'Day5', '最後一天'],
    rating: 4.8,
    review_count: 560,
  },

  // ══════════════════════════════════════════════════════
  // 親子友善餐廳（2-6歲）
  // ══════════════════════════════════════════════════════

  {
    id: 'r4',
    slug: 'matchandeul-wang-sogeum',
    name_ko: '맛찬들왕소금구이 서면점',
    name_zh: '맛찬들 鹽烤豬肉 西面店',
    name_en: 'Matchandeul Wang Sogeum Gui',
    type: 'restaurant',
    description: '釜山最多人推薦的豬五花連鎖名店。以天然岩鹽烤豬五花聞名，完全無辣，是帶小孩用餐的超安全選擇。自動叫號系統讓等待更輕鬆。',
    address_ko: '부산 부산진구 중앙대로691번가길 24-3',
    address_zh: '釜山釜山鎮區中央大路691巷24-3號',
    district: '西面',
    city: '釜山',
    lat: 35.1555,
    lng: 129.0587,
    image_url: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800&q=80',
    price_range: 'moderate',
    avg_price_krw: 18000,
    spice_level: 'none',
    cuisine_type: ['韓式烤肉', '豬五花'],
    kid_friendly_score: 5,
    kid_friendly_notes: '純鹽烤豬肉完全無辣，小孩直接吃。店員會幫忙烤和剪小塊。熱鬧環境小孩吵鬧也沒關係。',
    min_age: 1,
    has_english_menu: false,
    accepts_card: true,
    reservation_required: false,
    reservation_links: [
      {
        platform: 'Catch Table',
        url: 'https://global.catchtable.co.kr/ct/restaurants/search?keyword=%EB%A7%9B%EC%B0%AC%EB%93%A4%EC%99%95%EC%86%8C%EA%B8%88%EA%B5%AC%EC%9D%B4+%EC%84%9C%EB%A9%B4',
        label: 'Catch Table Global 查看',
        note: '無需預約，可查看等位狀況',
      },
      {
        platform: 'Naver',
        url: 'https://map.naver.com/v5/search/%EB%A7%9B%EC%B0%AC%EB%93%A4%EC%99%95%EC%86%8C%EA%B8%88%EA%B5%AC%EC%9D%B4+%EC%84%9C%EB%A9%B4%EC%A0%90',
        label: 'Naver Map 查看位置',
      },
      {
        platform: 'AutoReserve',
        url: 'https://autoreserve.com/en/restaurants/GbcEV3GwGU2vgvUx9SsS',
        label: '線上等位（AutoReserve）',
        note: '可線上加入候位，不用現場排隊',
      },
      {
        platform: 'Tabling',
        url: 'https://www.tabling.co.kr/restaurant/2116',
        label: 'Tabling 線上候位',
        note: '遠端候位，到附近再去取號',
      },
    ],
    recommended_dishes: [
      { name_ko: '왕소금구이', name_zh: '鹽烤豬五花', price_krw: 14000, description: '天然岩鹽調味，炭烤酥脆，完全無辣，小孩最愛', must_order: true },
      { name_ko: '계란찜', name_zh: '蒸蛋', price_krw: 2000, description: '軟嫩蒸蛋，小孩必點', must_order: true },
    ],
    ordering_tips: [
      '最低點3份，2人份可請店員確認',
      '烤鍋外圈同時煎蛋，說「계란 주세요」加點蛋',
      '幫小孩剪肉說「작게 잘라주세요」',
      '不需預約，用自動叫號機取號等候',
    ],
    review_summary: {
      pros: ['肉質水準穩定，是釜山最推薦的豬五花', '自動叫號不用站著排隊', '熱鬧環境帶小孩完全不尷尬', '蛋黃圈是亮點，小孩很愛'],
      cons: ['晚餐尖峰6-8點等待20-40分鐘', '只有豬肉，沒有牛肉或雞肉', '週末尤其需要耐心等候'],
    },
    opening_hours: { mon: '11:30-23:00', tue: '11:30-23:00', wed: '11:30-23:00', thu: '11:30-23:00', fri: '11:30-23:00', sat: '11:30-23:00', sun: '11:30-23:00' },
    tips: ['避開晚餐尖峰，建議5:30之前或8:30之後前往', '地鐵2號線西面站步行3分鐘'],
    tags: ['豬五花', '無辣', '親子', '西面', '必吃'],
    rating: 4.7,
    review_count: 3200,
  },

  {
    id: 'r5',
    slug: 'gaegeum-milmyeon',
    name_ko: '개금밀면',
    name_zh: '開琴小麥冷麵',
    name_en: 'Gaegeum Milmyeon',
    type: 'restaurant',
    description: '釜山獨有的「密麵（밀면）」名店，以小麥麵條製作，是釜山日常必吃的在地美食。清湯款完全無辣，水餃是小孩最愛，價格超實惠。',
    address_ko: '부산 부산진구 가야대로482번길 9-4',
    address_zh: '釜山釜山鎮區伽倻大路482巷9-4號',
    district: '開琴洞',
    city: '釜山',
    lat: 35.1571,
    lng: 129.0433,
    image_url: 'https://images.unsplash.com/photo-1569050467447-ce54b3bbc37d?w=800&q=80',
    price_range: 'budget',
    avg_price_krw: 10000,
    spice_level: 'mild',
    cuisine_type: ['冷麵', '釜山料理'],
    kid_friendly_score: 4,
    kid_friendly_notes: '清湯冷麵（물밀면）完全無辣，水餃完全無辣。拌麵（비빔밀면）可要求醬料分開放。',
    min_age: 1,
    has_english_menu: false,
    accepts_card: true,
    reservation_required: false,
    reservation_links: [
      {
        platform: 'Catch Table',
        url: 'https://global.catchtable.co.kr/ct/restaurants/search?keyword=%EA%B0%9C%EA%B8%88%EB%B0%80%EB%A9%B4',
        label: 'Catch Table Global 查看',
        note: '無需預約，直接前往',
      },
      {
        platform: 'Naver',
        url: 'https://map.naver.com/v5/search/%EA%B0%9C%EA%B8%88%EB%B0%80%EB%A9%B4',
        label: 'Naver Map 查看位置',
      },
    ],
    recommended_dishes: [
      { name_ko: '물밀면', name_zh: '清湯冷麵', price_krw: 10000, description: '牛骨清湯，完全無辣，Q彈麵條，小孩適合', must_order: true },
      { name_ko: '개금만두', name_zh: '開琴水餃', price_krw: 4000, description: '招牌水餃，無辣，小孩最愛，必點', must_order: true },
      { name_ko: '비빔밀면', name_zh: '辣拌冷麵', price_krw: 10000, description: '大人版，醬料可要求分開', must_order: false },
    ],
    ordering_tips: [
      '帶小孩點「물밀면（湯麵）」+ 「개금만두（水餃）」最安全',
      '辣醬分開說「양념 따로 주세요」',
      '麵條可幫小孩剪短「짧게 잘라주세요」',
    ],
    review_summary: {
      pros: ['釜山在地必吃，是真正的釜山日常味道', '水餃超好吃，份量實在', '價格超實惠，全家吃飽不到台幣500'],
      cons: ['店面較小，午餐尖峰可能等位', '環境簡單，無特別裝潢', '冷麵對2歲以下幼兒可能難以咀嚼'],
    },
    opening_hours: { mon: '11:00-21:00', tue: '11:00-21:00', wed: '11:00-21:00', thu: '11:00-21:00', fri: '11:00-21:00', sat: '11:00-21:00', sun: '11:00-20:00' },
    tips: ['午餐時段避開12-1點', '地鐵2號線開琴站附近'],
    tags: ['冷麵', '水餃', '釜山料理', '便宜', '無辣', '親子'],
    rating: 4.5,
    review_count: 1800,
  },

  {
    id: 'r6',
    slug: 'matchandeul-haeundae',
    name_ko: '맛찬들왕소금구이 해운대점',
    name_zh: '맛찬들 鹽烤豬肉 海雲台店',
    name_en: 'Matchandeul Haeundae',
    type: 'restaurant',
    description: '맛찬들連鎖海雲台分店，住在海雲台時步行可達。鹽烤豬五花無辣，帶小孩用餐最放心，性價比高。',
    address_ko: '부산 해운대구 해운대로',
    address_zh: '釜山海雲台區海雲台路（海雲台站附近）',
    district: '海雲台',
    city: '釜山',
    lat: 35.1628,
    lng: 129.1637,
    image_url: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800&q=80',
    price_range: 'moderate',
    avg_price_krw: 18000,
    spice_level: 'none',
    cuisine_type: ['韓式烤肉', '豬五花'],
    kid_friendly_score: 5,
    kid_friendly_notes: '同西面店，完全無辣，帶小孩非常適合。',
    min_age: 1,
    has_english_menu: false,
    accepts_card: true,
    reservation_required: false,
    reservation_links: [
      {
        platform: 'Catch Table',
        url: 'https://global.catchtable.co.kr/ct/restaurants/search?keyword=%EB%A7%9B%EC%B0%AC%EB%93%A4%EC%99%95%EC%86%8C%EA%B8%88%EA%B5%AC%EC%9D%B4+%ED%95%B4%EC%9A%B4%EB%8C%80',
        label: 'Catch Table Global 查看',
        note: '無需預約，可查看等位狀況',
      },
      {
        platform: 'Naver',
        url: 'https://map.naver.com/v5/search/%EB%A7%9B%EC%B0%AC%EB%93%A4%EC%99%95%EC%86%8C%EA%B8%88%EA%B5%AC%EC%9D%B4+%ED%95%B4%EC%9A%B4%EB%8C%80',
        label: 'Naver Map 查看位置',
      },
    ],
    recommended_dishes: [
      { name_ko: '왕소금구이', name_zh: '鹽烤豬五花', price_krw: 14000, description: '無辣，炭烤酥脆，小孩首選', must_order: true },
      { name_ko: '계란찜', name_zh: '蒸蛋', price_krw: 2000, description: '軟嫩蒸蛋，小孩必點', must_order: true },
    ],
    ordering_tips: ['同西面店點法，幫小孩剪肉說「작게 잘라주세요」'],
    review_summary: {
      pros: ['住海雲台時步行可達，最方便', '品質和西面店一樣穩定', '適合有小孩的家庭'],
      cons: ['同樣需要等候', '份量固定，帶1-2個小孩可能點太多'],
    },
    opening_hours: { mon: '11:30-23:00', tue: '11:30-23:00', wed: '11:30-23:00', thu: '11:30-23:00', fri: '11:30-23:00', sat: '11:30-23:00', sun: '11:30-23:00' },
    tips: ['住海雲台時的最佳親子晚餐選擇'],
    tags: ['豬五花', '無辣', '親子', '海雲台'],
    rating: 4.6,
    review_count: 1500,
  },

  // ══════════════════════════════════════════════════════
  // 親子友善公園（高評價 + 遊樂設施）
  // ══════════════════════════════════════════════════════

  {
    id: 'p1',
    slug: 'busan-childrens-grand-park',
    name_ko: '부산어린이대공원',
    name_zh: '釜山兒童大公園',
    name_en: "Busan Children's Grand Park",
    type: 'park',
    description: '釜山最大的兒童公園，有免費水樂園、4座年齡分區遊樂場、動物園「The Park」及森林步道。可以玩一整天，是釜山親子首選。',
    address_ko: '부산 부산진구 새싹로 295',
    address_zh: '釜山釜山鎮區新芽路295號',
    district: '釜山鎮區',
    city: '釜山',
    lat: 35.1725,
    lng: 129.0551,
    image_url: 'https://images.unsplash.com/photo-1575783970733-1aaedde1db74?w=800&q=80',
    price_range: 'free',
    ticket_price_free: true,
    ticket_price_krw: 0,
    time_needed_minutes: 240,
    best_time_to_visit: '平日上午9-11點最舒適，週末人多建議提早',
    kid_friendly_score: 5,
    kid_friendly_notes: '專為兒童設計，有0-6歲幼兒區遊樂場。免費水樂園有防滑地面和救生員。適合2-6歲全年齡。',
    min_age: 0,
    review_summary: {
      pros: ['免費入場是最大優點，大家一致肯定', '4個分年齡遊樂場，2歲到10歲都有適合設施', '免費水樂園地面防滑，安全又好玩', '有動物園可以延伸一天行程'],
      cons: ['週末和假日非常擁擠，建議10點前到', '大型攀爬結構適合5歲以上，2-3歲需緊密陪同', '動物園需另外付費（₩15,000/兒童）', '停車位週末很搶手'],
    },
    opening_hours: { mon: '09:00-18:00', tue: '09:00-18:00', wed: '09:00-18:00', thu: '09:00-18:00', fri: '09:00-18:00', sat: '09:00-18:00', sun: '09:00-18:00', note: '水樂園：10:00-17:00，週一休息' },
    tips: [
      '公園本身免費，動物園兒童₩15,000另付',
      '夏天記得帶泳衣和備用衣服去玩水樂園',
      '從西面站搭54、81、133號公車直達',
    ],
    tags: ['免費', '公園', '遊樂場', '水樂園', '動物園', '親子', '幼兒'],
    rating: 4.7,
    review_count: 5200,
  },

  {
    id: 'p2',
    slug: 'busan-citizens-park',
    name_ko: '부산시민공원',
    name_zh: '釜山市民公園',
    name_en: 'Busan Citizens Park',
    type: 'park',
    description: '釜山最大的城市公園，2025年12月新開放免費室內公共兒童咖啡廳。9個不同主題遊樂區、夏日免費水廣場、螺旋塔溜滑梯，適合全天親子出遊。',
    address_ko: '부산 부산진구 시민공원로 73',
    address_zh: '釜山釜山鎮區市民公園路73號',
    district: '釜山鎮區',
    city: '釜山',
    lat: 35.1607,
    lng: 129.0554,
    image_url: 'https://images.unsplash.com/photo-1568702846914-96b305d2aaeb?w=800&q=80',
    price_range: 'free',
    ticket_price_free: true,
    time_needed_minutes: 180,
    best_time_to_visit: '平日下午2-5點，春秋兩季最舒適',
    kid_friendly_score: 5,
    kid_friendly_notes: '全區無障礙設計，推車可通行。2025年12月新開室內免費兒童咖啡廳（0-7歲），雨天也能玩。夏日水廣場免費，每2小時噴水25分鐘。',
    min_age: 0,
    review_summary: {
      pros: ['推車友善，全區鋪設無障礙步道', '9個遊樂主題區，玩3-4小時都不夠', '室內兒童咖啡廳2025年底新開，免費，雨天救星', '螺旋塔溜滑梯是必玩打卡設施'],
      cons: ['主水廣場週末非常擁擠', '螺旋塔和複雜攀爬結構適合4歲以上', '公園很大，帶幼兒走完全程體力消耗大', '夏日戶外區日曬強，需防曬'],
    },
    opening_hours: { mon: '05:00-23:00', tue: '05:00-23:00', wed: '05:00-23:00', thu: '05:00-23:00', fri: '05:00-23:00', sat: '05:00-23:00', sun: '05:00-23:00', note: '室內兒童咖啡廳：週二-六 10:00-17:20，週日一休館' },
    tips: [
      '地鐵1號線釜田站或蓋金站步行可達',
      '室內兒童咖啡廳雨天必去，0-7歲免費',
      '水廣場運作時間：10:30-19:30，每2小時25分鐘噴水',
    ],
    tags: ['免費', '公園', '遊樂場', '推車友善', '室內', '幼兒', '水廣場'],
    rating: 4.6,
    review_count: 4100,
  },

  {
    id: 'p3',
    slug: 'sujeongsan-dream-site',
    name_ko: '수정산 드림사이트',
    name_zh: '水晶山夢想遊樂場',
    name_en: 'Sujeongsan Dream Site',
    type: 'park',
    description: '2024年新開幕的大型戶外兒童遊樂場，面積近2.2萬平方公尺，有溜滑梯、隧道、飛索、彈跳床，是釜山最新、最酷的免費遊樂場。',
    address_ko: '부산 동구 수정산',
    address_zh: '釜山東區水晶山',
    district: '東區',
    city: '釜山',
    lat: 35.1200,
    lng: 129.0480,
    image_url: 'https://images.unsplash.com/photo-1516627145497-ae6968895b74?w=800&q=80',
    price_range: 'free',
    ticket_price_free: true,
    time_needed_minutes: 120,
    best_time_to_visit: '平日上午，人少設施不用等',
    kid_friendly_score: 4,
    kid_friendly_notes: '整體適合4-6歲，2-3歲部分設施（飛索、高溜滑梯）需大人陪同或暫不適合。彈跳床和低溜滑梯適合2歲以上。2024年新開，評價極佳。',
    min_age: 2,
    review_summary: {
      pros: ['2024年新開幕，設施全新乾淨', '面積超大，設施種類豐富不重複', '免費入場，釜山CP值最高的遊樂場之一', '環保材質設計，安全性高'],
      cons: ['位於山上，推車靠近路口後可能有坡度', '飛索等高空設施建議4歲以上', '新設施評價尚少，建議出發前確認開放狀態', '日曬強，記得帶防曬和帽子'],
    },
    opening_hours: { tue: '09:00-18:00', wed: '09:00-18:00', thu: '09:00-18:00', fri: '09:00-18:00', sat: '09:00-18:00', sun: '09:00-18:00', note: '週一休館' },
    tips: ['13歲以下兒童免費，需成人陪同', '備妥防曬，戶外全日曝曬'],
    tags: ['免費', '新開幕', '遊樂場', '飛索', '溜滑梯', '戶外'],
    rating: 4.5,
    review_count: 320,
  },

  {
    id: 'p4',
    slug: 'songdo-sky-park',
    name_ko: '송도 해상케이블카 공원',
    name_zh: '松島海上纜車公園',
    name_en: 'Songdo Sky Park',
    type: 'park',
    description: '松島海岸的特色公園，有超巨大蝸牛造型溜滑梯、恐龍裝置藝術，以及透明玻璃海上步道，小孩超愛的海邊公園！',
    address_ko: '부산 서구 암남공원로 185',
    address_zh: '釜山西區巖南公園路185號',
    district: '西區',
    city: '釜山',
    lat: 35.0590,
    lng: 129.0137,
    image_url: 'https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?w=800&q=80',
    price_range: 'free',
    ticket_price_free: true,
    time_needed_minutes: 90,
    best_time_to_visit: '下午4點後，光線美，人相對少',
    kid_friendly_score: 4,
    kid_friendly_notes: '巨大蝸牛溜滑梯和恐龍裝置是小孩超愛的重點。玻璃步道透明底部有些小孩會害怕，2-3歲幼兒需抱著通過。纜車若搭乘需確認身高限制。',
    min_age: 1,
    review_summary: {
      pros: ['巨大蝸牛溜滑梯是孩子最愛，IG打卡必去', '恐龍裝置讓小孩興奮尖叫', '免費進入公園，纜車另計', '海邊景色美，大人也很喜歡'],
      cons: ['玻璃底步道高度讓部分幼兒害怕', '週末纜車大排長龍，建議平日前往', '夏天戶外熱，帶嬰幼兒要注意防曬', '停車費另計'],
    },
    opening_hours: { mon: '09:00-18:00', tue: '09:00-18:00', wed: '09:00-18:00', thu: '09:00-18:00', fri: '09:00-21:00', sat: '09:00-21:00', sun: '09:00-21:00', note: '纜車：大人₩15,000，3歲以下免費' },
    tips: ['地鐵1號線土城站搭公車或計程車約10分鐘', '蝸牛溜滑梯旁有小型遊樂設施'],
    tags: ['公園', '溜滑梯', '海景', '打卡', '蝸牛', '恐龍', '親子'],
    rating: 4.4,
    review_count: 2800,
  },

  // ══════════════════════════════════════════════════════
  // 親子友善景點
  // ══════════════════════════════════════════════════════

  {
    id: 'a1',
    slug: 'sealife-busan-aquarium',
    name_ko: '씨라이프 부산아쿠아리움',
    name_zh: 'SEA LIFE 釜山水族館',
    name_en: 'SEA LIFE Busan Aquarium',
    type: 'attraction',
    description: '海雲台海灘旁的人氣水族館，3萬5千多隻海洋生物、鯊魚隧道步道、企鵝表演，是帶2-6歲小孩最棒的室內景點。冷氣充足，雨天必去。',
    address_ko: '부산 해운대구 해운대해변로 266',
    address_zh: '釜山海雲台區海雲台海邊路266號',
    district: '海雲台',
    city: '釜山',
    lat: 35.1582,
    lng: 129.1598,
    image_url: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=800&q=80',
    price_range: 'moderate',
    ticket_price_krw: 31000,
    ticket_price_free: false,
    booking_url: 'https://www.visitsealife.com/busan/en/tickets-passes/',
    time_needed_minutes: 120,
    best_time_to_visit: '平日上午10-12點，人最少',
    kid_friendly_score: 5,
    kid_friendly_notes: '36個月以下免費（需出示證件）。鯊魚隧道讓2歲小孩也會超興奮。全館有電梯，推車友善。韓國多個親子旅遊部落客列為釜山親子首選。',
    min_age: 0,
    reservation_links: [
      {
        platform: 'Official',
        url: 'https://www.visitsealife.com/busan/en/tickets-passes/',
        label: '官網購票（最多省30%）',
        note: '線上購票直接掃QR入場，不用排隊',
      },
      {
        platform: 'KKday',
        url: 'https://www.kkday.com/en-us/product/2880-sea-life-busan-aquarium-tickets-korea',
        label: 'KKday 購票',
      },
      {
        platform: 'Klook',
        url: 'https://www.klook.com/en-US/activity/1251-sea-life-aquarium-busan/',
        label: 'Klook 購票',
      },
    ],
    review_summary: {
      pros: ['鯊魚隧道是小孩最驚喜的體驗，3歲也會目瞪口呆', '36個月以下免費，減輕費用壓力', '冷氣舒適，夏天雨天都適合', '企鵝、水獺、水母展區讓小孩流連忘返'],
      cons: ['週末和假日排隊長，建議提前網購跳過人龍', '部分展示區有些昏暗，2歲幼兒可能緊張', '館內餐廳選擇少，建議前後到外面吃飯', '票價不含特別表演，需另外確認'],
    },
    opening_hours: { mon: '10:00-19:00', tue: '10:00-19:00', wed: '10:00-19:00', thu: '10:00-19:00', fri: '10:00-19:00', sat: '10:00-20:00', sun: '10:00-20:00', note: '最後入場比閉館早1小時' },
    tips: [
      '網購比現場最多省30%！',
      '3歲以下帶出生證明可免費入場',
      '從海雲台站步行5分鐘，與海灘可以合併一天行程',
    ],
    tags: ['水族館', '鯊魚', '室內', '雨天', '親子', '海雲台', '必去'],
    rating: 4.5,
    review_count: 8900,
  },

  {
    id: 'a2',
    slug: 'national-maritime-museum',
    name_ko: '국립해양박물관',
    name_zh: '國立海洋博物館',
    name_en: 'National Maritime Museum of Korea',
    type: 'attraction',
    description: '完全免費的海洋博物館，館內有專為5歲以下設計的「섬마을 놀이터（島村遊樂場）」、兒童博物館、小型水族館，可停留2-3小時，是最佳免費親子景點。',
    address_ko: '부산 영도구 해양로301번길 45',
    address_zh: '釜山影島區海洋路301巷45號',
    district: '影島',
    city: '釜山',
    lat: 35.0810,
    lng: 129.0724,
    image_url: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80',
    price_range: 'free',
    ticket_price_free: true,
    time_needed_minutes: 150,
    best_time_to_visit: '平日上午，人少設施都能玩到',
    kid_friendly_score: 5,
    kid_friendly_notes: '2樓兒童博物館和「섬마을 놀이터」是專為幼兒設計的互動區，需1名大人陪同入場。全館電梯，推車可通行。館內有咖啡廳。',
    min_age: 1,
    reservation_links: [
      {
        platform: 'Official',
        url: 'https://www.mmk.or.kr/mobile/eng/?folder=exhibition&page=kids',
        label: '官網查看兒童展覽資訊',
      },
    ],
    review_summary: {
      pros: ['完全免費，是釜山最超值的親子景點', '幼兒互動遊樂場專為5歲以下設計', '館內有免費小型水族館', '全館推車可通行，電梯完善'],
      cons: ['週一休館，出發前務必確認', '影島位置稍遠，需搭計程車或公車', '主要海洋歷史展區對幼兒吸引力較低，專注去兒童區即可', '部分說明牌以韓文為主'],
    },
    opening_hours: { tue: '09:00-18:00', wed: '09:00-18:00', thu: '09:00-18:00', fri: '09:00-18:00', sat: '09:00-21:00', sun: '09:00-19:00', note: '週一公休，新年、春節、中秋休館' },
    tips: ['週一休館，行程安排要注意', '從南浦洞搭計程車約15分鐘，₩8,000左右', '免費小型水族館在館內'],
    tags: ['免費', '博物館', '幼兒', '室內', '雨天', '影島', '推車友善'],
    rating: 4.6,
    review_count: 3400,
  },

  {
    id: 'a3',
    slug: 'blueline-park',
    name_ko: '해운대 블루라인파크',
    name_zh: '海雲台藍線公園（天空膠囊 + 海灘小火車）',
    name_en: 'Haeundae Blueline Park',
    type: 'attraction',
    description: '沿海岸舊鐵道改建的觀光路線，分「天空膠囊（4人艙）」和「海灘小火車」。全程4.8公里欣賞東海海景。帶小孩建議搭海灘小火車更舒適安全。',
    address_ko: '부산 해운대구 달맞이길 62번길 11 (미포정류장)',
    address_zh: '釜山海雲台區迎月路62巷11號（尾浦乘車站）',
    district: '海雲台',
    city: '釜山',
    lat: 35.1627,
    lng: 129.1715,
    image_url: 'https://images.unsplash.com/photo-1501594907352-04cda38ebc29?w=800&q=80',
    price_range: 'moderate',
    ticket_price_krw: 8000,
    ticket_price_free: false,
    booking_url: 'https://www.bluelinepark.com/eng/booking.do',
    time_needed_minutes: 90,
    best_time_to_visit: '晴天早上9-11點，光線最美',
    kid_friendly_score: 4,
    kid_friendly_notes: '36個月以下免費。帶幼兒強烈推薦「海灘小火車」而非天空膠囊：空間寬敞、通風、沒有密閉感，且可以在各站下車。天空膠囊夏天無冷氣、密閉空間可能讓幼兒不舒服。',
    min_age: 0,
    reservation_links: [
      {
        platform: 'Official',
        url: 'https://www.bluelinepark.com/eng/booking.do',
        label: '官網訂票（建議提前）',
        note: '天空膠囊週末秒殺，需提前訂；小火車現場排隊購票即可',
      },
      {
        platform: 'KKday',
        url: 'https://www.kkday.com/en-us/product/123012-haeundae-blueline-park-beach-train-sky-capsule-ticket-korea',
        label: 'KKday 購票',
      },
    ],
    review_summary: {
      pros: ['沿海岸鐵道的景觀獨一無二，照片超美', '海灘小火車空間寬敞，帶小孩輕鬆', '36個月以下免費', '天空膠囊4人共享，拍照體驗感佳'],
      cons: ['天空膠囊夏天無冷氣，密閉悶熱不適合幼兒', '天空膠囊週末很難訂，需提前幾週', '海灘小火車現場購票可能等候', '折返需搭同方向，規劃時間要預留'],
    },
    opening_hours: { mon: '09:00-17:30', tue: '09:00-17:30', wed: '09:00-17:30', thu: '09:00-17:30', fri: '09:00-17:30', sat: '09:00-17:30', sun: '09:00-17:30', note: '天空膠囊每次週二開放4週後的預約' },
    tips: [
      '帶幼兒首選海灘小火車（해변열차），票價₩8,000-10,000',
      '天空膠囊（스카이캡슐）₩30,000/艙，適合大人或較大孩子',
      '尾浦站（미포정류장）在海雲台海灘東端步行5分鐘',
    ],
    tags: ['海景', '觀光', '火車', '膠囊', '海雲台', '親子', '特色體驗'],
    rating: 4.6,
    review_count: 6200,
  },

  {
    id: 'a4',
    slug: 'lotte-world-busan',
    name_ko: '롯데월드 어드벤처 부산',
    name_zh: '樂天世界冒險 釜山',
    name_en: 'Lotte World Adventure Busan',
    type: 'attraction',
    description: '釜山唯一主題樂園（2022年開幕），設有幼兒專區「歡樂牧場」6項適合2-6歲的遊樂設施：餅乾小火車、旋轉木馬、小農場等，是釜山親子一日遊的熱門選擇。',
    address_ko: '부산 기장군 기장읍 동부산관광로 42',
    address_zh: '釜山機張郡機張邑東釜山觀光路42號',
    district: '機張',
    city: '釜山',
    lat: 35.2285,
    lng: 129.2234,
    image_url: 'https://images.unsplash.com/photo-1513889961551-628c1e5e2ee9?w=800&q=80',
    price_range: 'expensive',
    ticket_price_krw: 33000,
    ticket_price_free: false,
    booking_url: 'https://adventure.lotteworld.com/eng/',
    time_needed_minutes: 360,
    best_time_to_visit: '平日開門（10點）就進，幼兒區幾乎沒排隊',
    kid_friendly_score: 4,
    kid_friendly_notes: '「歡樂牧場」幼兒專區有6項無身高限制的設施，2歲就可以玩。36個月以下₩12,000（低收費入場）。室內外混合，冷熱天都有去處。',
    min_age: 1,
    reservation_links: [
      {
        platform: 'Official',
        url: 'https://adventure.lotteworld.com/eng/price/gstt/information/list.do',
        label: '官網購票',
      },
      {
        platform: 'KKday',
        url: 'https://www.kkday.com/en/product/19296-busan-lotte-world-adventure-tickets-korea',
        label: 'KKday 購票（可享優惠）',
      },
      {
        platform: 'Klook',
        url: 'https://www.klook.com/en-US/activity/75094-lotte-world-busan/',
        label: 'Klook 購票',
      },
    ],
    review_summary: {
      pros: ['釜山唯一主題樂園，有獨特性', '幼兒專區設施專為小孩設計，無身高限制', '冬天有室內設施可避寒', '有豐富餐飲選擇，解決吃飯問題'],
      cons: ['位於機張，離海雲台30-40分鐘車程', '僅有幼兒的家庭，可玩設施有限，票價偏貴', '熱門設施週末排隊長，帶幼兒體力消耗大', '嬰兒車可借用但數量有限'],
    },
    opening_hours: { mon: '10:00-20:00', tue: '10:00-20:00', wed: '10:00-20:00', thu: '10:00-20:00', fri: '10:00-20:00', sat: '10:00-21:00', sun: '10:00-21:00' },
    tips: [
      '兒童（3-12歲）₩33,000，36個月以下₩12,000',
      'KKday / Klook 購票通常有9折優惠',
      '幼兒專區「즐거운 목장」在入場後左手邊',
      '從海雲台搭計程車約₩30,000，30-40分鐘',
    ],
    tags: ['主題樂園', '幼兒設施', '室內', '一日遊', '機張', '親子'],
    rating: 4.3,
    review_count: 4700,
  },

  // ══════════════════════════════════════════════════════
  // 購物 / 折扣資訊
  // ══════════════════════════════════════════════════════

  {
    id: 's1',
    slug: 'shinsegae-centum-city',
    name_ko: '신세계백화점 센텀시티점',
    name_zh: '新世界百貨 Centum City（全球最大百貨）',
    name_en: 'Shinsegae Centum City',
    type: 'shopping',
    description: '金氏世界紀錄認定的全球最大百貨公司，館內有 KidZania、Spa Land、溜冰場、電影院、屋頂主題公園。外國旅客可到B1外國顧客服務台領取專屬折扣券！',
    address_ko: '부산 해운대구 센텀남대로 35',
    address_zh: '釜山海雲台區Centum南大路35號',
    district: 'Centum/海雲台',
    city: '釜山',
    lat: 35.1688,
    lng: 129.1308,
    image_url: 'https://images.unsplash.com/photo-1441984904996-e0b6ba687e04?w=800&q=80',
    price_range: 'moderate',
    kid_friendly_score: 4,
    kid_friendly_notes: '館內有 KidZania（3歲以上，需另買票）、屋頂主題公園、溜冰場。全館推車友善，電梯完善。外國旅客可在B1服務台領取外國人專屬折扣券。',
    time_needed_minutes: 240,
    reservation_links: [
      {
        platform: 'Official',
        url: 'https://english.visitkorea.or.kr/svc/contents/contentsView.do?vcontsId=217965',
        label: '外國旅客折扣券說明',
        note: '持護照至B1外國顧客服務台領取，現場兌換',
      },
      {
        platform: 'KKday',
        url: 'https://www.kkday.com/en/product/35042-kidzania-busan-tickets-korea',
        label: 'KKday 購買 KidZania 門票',
      },
    ],
    review_summary: {
      pros: ['全球最大百貨，選擇多元，品牌齊全', '外國旅客B1服務台有專屬折扣券和退稅服務', '館內設施超多，一整天都逛不完', 'KidZania 在館內，親子購物一條龍'],
      cons: ['面積太大容易迷路，建議先看地圖', '週末人潮洶湧，帶幼兒較吃力', 'KidZania 需另購票，排隊設施等候長', '每月第4個週一公休'],
    },
    opening_hours: { mon: '10:30-20:00', tue: '10:30-20:00', wed: '10:30-20:00', thu: '10:30-20:00', fri: '10:30-20:30', sat: '10:30-20:30', sun: '10:30-20:30', note: '每月第4個週一公休；餐廳區通常延長至21:00' },
    tips: [
      '🎫 外國旅客必去B1「외국인 고객 서비스 데스크」領取折扣券！',
      '💰 出示護照可辦理即時退稅（VAT退稅6-8%，最高₩100萬/單品）',
      '🚇 地鐵2號線 Centum City 站地下直通',
      '👶 KidZania（3-16歲，₩35,000-45,000）需提前網路預約',
    ],
    tags: ['購物', '折扣', '退稅', 'KidZania', 'Spa', '全球最大', '海雲台'],
    rating: 4.5,
    review_count: 12000,
  },

  {
    id: 's2',
    slug: 'visit-busan-pass',
    name_ko: '비짓부산패스',
    name_zh: 'Visit Busan Pass（外國人專屬旅遊卡）',
    name_en: 'Visit Busan Pass',
    type: 'shopping',
    description: '釜山外國旅客專屬旅遊卡，一張卡涵蓋40+景點免費入場（含水族館、SpaLand、海灘小火車等）+160+餐廳購物折扣。24小時卡₩49,000，省超多！',
    address_ko: '부산 전역 (온라인 구매)',
    address_zh: '釜山全區通用（線上購買）',
    district: '全釜山',
    city: '釜山',
    lat: 35.1796,
    lng: 129.0756,
    image_url: 'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=800&q=80',
    price_range: 'moderate',
    ticket_price_krw: 49000,
    ticket_price_free: false,
    booking_url: 'https://www.visitbusanpass.com/',
    time_needed_minutes: 0,
    kid_friendly_score: 5,
    kid_friendly_notes: '包含SEA LIFE水族館、海灘小火車、SpaLand等親子景點，外國人專屬，持護照購買。建議一天密集玩景點時使用，效益最大。',
    reservation_links: [
      {
        platform: 'Official',
        url: 'https://www.visitbusanpass.com/',
        label: '官網購買 Visit Busan Pass',
      },
      {
        platform: 'Klook',
        url: 'https://www.klook.com/en-US/activity/81576-visit-busan-pass/',
        label: 'Klook 購買',
      },
      {
        platform: 'KKday',
        url: 'https://www.kkday.com/en/product/145568-visit-busan-pass',
        label: 'KKday 購買',
      },
    ],
    review_summary: {
      pros: ['涵蓋景點多，安排密集時非常划算', 'SEA LIFE + 海灘小火車 + SpaLand 三個加起來就回本', '使用方便，手機掃QR入場', '外國人專屬，韓國人不能買'],
      cons: ['24小時計時從第一個使用景點開始，需集中使用', '部分熱門景點仍需另外預約（如天空膠囊）', '部分景點淡季或暫停無法使用，建議出發前確認', '需有網路才能使用手機版'],
    },
    opening_hours: { note: '線上購買，6個月內啟用有效，啟用後24/48小時有效' },
    tips: [
      '💡 含SEA LIFE(₩31,000) + 藍線公園小火車(₩10,000) + SpaLand(₩18,000) = ₩59,000，24H卡₩49,000 直接省錢！',
      '📱 購買後下載到手機，掃QR進場',
      '🎯 安排景點集中的那天使用效益最大',
    ],
    tags: ['旅遊卡', '折扣', '外國人', '省錢', '必買', '含景點'],
    rating: 4.4,
    review_count: 2100,
  },
]

// ══════════════════════════════════════════════════════════
// 輔助資料
// ══════════════════════════════════════════════════════════

export const typeLabels: Record<string, string> = {
  restaurant: '餐廳',
  cafe: '咖啡廳',
  attraction: '景點',
  park: '公園',
  shopping: '購物/票券',
  activity: '活動',
}

export const spiceLevelLabels: Record<string, string> = {
  none: '完全無辣 ✅',
  mild: '微辣（可調整）⚠️',
  moderate: '中辣 🌶',
  spicy: '辣 🌶🌶',
}

export const priceLabels: Record<string, string> = {
  free: '免費',
  budget: '便宜 (₩10,000以下)',
  moderate: '中等 (₩10,000–30,000)',
  expensive: '高價 (₩30,000+)',
  luxury: '奢華',
}

export const districts = [
  { id: 'all', name: '全部' },
  { id: '海雲台', name: '海雲台' },
  { id: '西面', name: '西面' },
  { id: '釜山鎮區', name: '釜山鎮區' },
  { id: 'Centum/海雲台', name: 'Centum' },
  { id: '機張', name: '機張' },
  { id: '東區', name: '東區' },
  { id: '西區', name: '西區' },
  { id: '影島', name: '影島' },
  { id: '全釜山', name: '全釜山' },
]

export const filterTypes = [
  { id: 'all', label: '全部' },
  { id: 'restaurant', label: '🍽 餐廳' },
  { id: 'park', label: '🌳 公園' },
  { id: 'attraction', label: '🎡 景點' },
  { id: 'shopping', label: '🛍 購物/票券' },
]

// ══════════════════════════════════════════════════════════
// 行程模板
// ══════════════════════════════════════════════════════════

export const suggestedItineraries: SuggestedItinerary[] = [
  {
    id: 'busan-5days-personal',
    title: '你的釜山5天行程',
    days: 5,
    description: '個人行程：Day2烤牛、Day3海鮮、Day5米其林鰻魚，每晚包車接送',
    image_url: 'https://images.unsplash.com/photo-1519984388953-d2406bc725e1?w=600&q=80',
    spotIds: ['r1', 'r2', 'r3'],
    schedule: [
      { day: 1, title: 'Day 1 抵達釜山・自由活動', items: [] },
      {
        day: 2, title: 'Day 2（4/2）包車 → 烤牛晚餐',
        items: [{ spotId: 'r1', start: '19:00', duration: 120, note: '傳說肋排，包車回來後前往，務必提前訂位' }],
      },
      {
        day: 3, title: 'Day 3（4/3）包車 → 海鮮晚餐',
        items: [{ spotId: 'r2', start: '19:00', duration: 120, note: '海賊飯廊，帝王蟹＋烤鮑魚' }],
      },
      { day: 4, title: 'Day 4 自由活動', items: [] },
      {
        day: 5, title: 'Day 5 最後一天 → 米其林壓軸',
        items: [{ spotId: 'r3', start: '18:30', duration: 120, note: '海木米其林鰻魚，旅程最完美的句點' }],
      },
    ],
  },
  {
    id: 'busan-kids-day',
    title: '釜山親子一日精華',
    days: 1,
    description: '適合2-6歲小孩的一天行程：水族館→公園→親子晚餐，全程無辣',
    image_url: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=600&q=80',
    spotIds: ['a1', 'p2', 'r4'],
    schedule: [
      {
        day: 1, title: '親子完整一天',
        items: [
          { spotId: 'a1', start: '10:00', duration: 120, note: 'SEA LIFE水族館，3歲以下免費，提前網購省30%' },
          { spotId: 'p2', start: '13:30', duration: 150, note: '市民公園，午餐後散步玩遊樂場' },
          { spotId: 'r4', start: '18:00', duration: 90, note: '맛찬들鹽烤豬肉，完全無辣，小孩最愛' },
        ],
      },
    ],
  },
  {
    id: 'busan-kids-park-tour',
    title: '釜山公園遊樂場巡禮',
    days: 2,
    description: '兩天玩遍釜山最棒的親子公園，全部免費，2-6歲必訪',
    image_url: 'https://images.unsplash.com/photo-1575783970733-1aaedde1db74?w=600&q=80',
    spotIds: ['p1', 'r5', 'p2', 'a2', 'r4'],
    schedule: [
      {
        day: 1, title: '兒童大公園＋開琴冷麵',
        items: [
          { spotId: 'p1', start: '09:30', duration: 240, note: '釜山兒童大公園，帶泳衣玩免費水樂園！' },
          { spotId: 'r5', start: '12:00', duration: 60, note: '開琴밀면，清湯冷麵+水餃，無辣又便宜' },
        ],
      },
      {
        day: 2, title: '市民公園＋海洋博物館',
        items: [
          { spotId: 'p2', start: '10:00', duration: 150, note: '市民公園，室內兒童咖啡廳（雨天備案）' },
          { spotId: 'a2', start: '14:00', duration: 150, note: '國立海洋博物館，完全免費！幼兒互動區' },
          { spotId: 'r4', start: '18:30', duration: 90, note: '맛찬들鹽烤豬肉收尾' },
        ],
      },
    ],
  },
]
