import { Spot, SuggestedItinerary } from './types'

export const spots: Spot[] = [

  // ══════════════════════════════════════════════════════
  // 你的行程餐廳（Day 2 / 3 / 5）
  // ══════════════════════════════════════════════════════

  {
    id: 'r1',
    slug: 'ribs-of-legend-haeundae',
    name_ko: '리브스 오브 레전드 해운대',
    name_zh: '傳說肋排 海雲台店',
    name_en: 'Ribs of Legend Haeundae',
    type: 'restaurant',
    description: '海雲台海灘旁3樓的高級韓式烤牛名店，以頂級牛肋排聞名，肉質油花豐富。窗邊座位可眺望海雲台海灘夜景，是 Day 2 晚餐首選。',
    address_ko: '부산 해운대구 해운대해변로 277 3층',
    address_zh: '釜山海雲台區海雲台海邊路277號 3樓',
    district: '海雲台',
    city: '釜山',
    lat: 35.1631,
    lng: 129.1604,
    image_url: 'https://images.unsplash.com/photo-1529692236671-f1f6cf9683ba?w=800&q=80',
    price_range: 'expensive',
    avg_price_krw: 60000,
    spice_level: 'none',
    cuisine_type: ['韓式烤肉', '烤牛'],
    kid_friendly_score: 3,
    kid_friendly_notes: '烤肉由店員操作，可為小孩切小塊。環境較安靜高級，小孩若吵鬧可能不方便。',
    has_english_menu: false,
    accepts_card: true,
    reservation_required: true,
    reservation_links: [
      {
        platform: 'Catch Table',
        url: 'https://www.catchtable.net/',
        label: 'Catch Table Global 訂位',
        note: 'App 開啟後搜尋「리브스 오브 레전드」',
      },
    ],
    staff_phrases: [
      { situation: '我們幾個人（例：4人）', korean: '네 명이요' },
      { situation: '有靠窗/海景的位置嗎？', korean: '바다 보이는 자리 있어요?' },
      { situation: '幫小孩把肉切小塊', korean: '아이 거 작게 잘라 주세요' },
      { situation: '不要太辣 / 完全不辣', korean: '안 맵게 해 주세요' },
      { situation: '要一杯水', korean: '물 주세요' },
      { situation: '有嬰兒椅嗎？', korean: '아기 의자 있어요?' },
      { situation: '結帳', korean: '계산해 주세요' },
      { situation: '刷卡可以嗎？', korean: '카드 돼요?' },
    ],
    recommended_dishes: [
      { name_ko: '꽃등심', name_zh: '花紋肋眼', price_krw: 65000, description: '招牌！油花均勻，炭火烤出外焦內嫩', must_order: true },
      { name_ko: '갈비살', name_zh: '牛肋排肉', price_krw: 55000, description: '帶骨牛肋肉，口感豐富香氣十足', must_order: true },
    ],
    ordering_tips: [
      '烤肉由店員操作，不需自己烤',
      '海景座位說「바다 보이는 자리 주세요」',
      '小孩的肉請店員剪小塊「작게 잘라주세요」',
    ],
    review_summary: {
      pros: ['海景窗邊座位絕美，適合特別場合', '肉質水準穩定、油花豐富', '店員服務好會主動幫切肉'],
      cons: ['價格偏高，人均約台幣1,500以上', '週末需提前至少一週訂位', '環境較正式，帶小小孩可能有壓力'],
    },
    opening_hours: { mon: '17:00-23:00', tue: '17:00-23:00', wed: '17:00-23:00', thu: '17:00-23:00', fri: '17:00-00:00', sat: '12:00-00:00', sun: '12:00-23:00' },
    tips: ['Day 2（4/2）晚餐，包車回來後前往', '飯後沿海雲台海灘散步消化'],
    tags: ['烤牛', '海景', '高級', 'Day2', '4/2'],
    rating: 4.6,
    review_count: 890,
  },

  {
    id: 'r2',
    slug: 'haejok-ssallong-haeundae',
    name_ko: '해적쌀롱 해운대본점',
    name_zh: '海賊飯廊 海雲台本店',
    name_en: 'Haejok Ssallong Haeundae',
    type: 'restaurant',
    description: '海雲台人氣海鮮餐廳，提供釜山在地新鮮漁獲，炭火燒烤或生食皆有。帝王蟹、鮑魚、海鮮鍋是招牌，是 Day 3 晚餐的絕佳選擇。',
    address_ko: '부산 해운대구 구남로12번길 8 1층, 2층',
    address_zh: '釜山海雲台區九南路12巷8號 1-2樓',
    district: '海雲台',
    city: '釜山',
    lat: 35.1585,
    lng: 129.1602,
    image_url: 'https://images.unsplash.com/photo-1519984388953-d2406bc725e1?w=800&q=80',
    price_range: 'expensive',
    avg_price_krw: 50000,
    spice_level: 'mild',
    cuisine_type: ['海鮮', '活海鮮'],
    kid_friendly_score: 3,
    kid_friendly_notes: '蒸帝王蟹、烤鮑魚都是無辣料理，小孩可吃。帶孩子建議點蒸類而非辣湯鍋。',
    has_english_menu: false,
    accepts_card: true,
    reservation_required: true,
    reservation_links: [
      {
        platform: 'Catch Table',
        url: 'https://www.catchtable.net/',
        label: 'Catch Table Global 訂位',
        note: 'App 開啟後搜尋「해적쌀롱」',
      },
    ],
    staff_phrases: [
      { situation: '我們幾個人（例：4人）', korean: '네 명이요' },
      { situation: '帝王蟹現在多少錢？', korean: '킹크랩 지금 얼마예요?' },
      { situation: '要蒸的，不要辣', korean: '찜으로 해 주세요. 안 맵게요' },
      { situation: '幫小孩把蟹肉取出來', korean: '아이 거 살 발라 주세요' },
      { situation: '要一碗白飯', korean: '공기밥 주세요' },
      { situation: '要一杯水', korean: '물 주세요' },
      { situation: '有嬰兒椅嗎？', korean: '아기 의자 있어요?' },
      { situation: '結帳', korean: '계산해 주세요' },
    ],
    recommended_dishes: [
      { name_ko: '킹크랩（蒸）', name_zh: '清蒸帝王蟹', price_krw: 150000, description: '活體帝王蟹現點現蒸，鮮甜無辣，小孩可吃', must_order: true },
      { name_ko: '전복구이', name_zh: '烤鮑魚', price_krw: 30000, description: '炭火烤鮑魚加奶油，香氣四溢無辣', must_order: true },
      { name_ko: '해물탕', name_zh: '海鮮鍋', price_krw: 60000, description: '辣湯鍋，成人適合，小孩避開', must_order: false },
    ],
    ordering_tips: [
      '帶小孩建議點「찜（蒸）」而非辣鍋',
      '帝王蟹按市價，點前確認價格「얼마예요?」',
      '白飯加點說「공기밥 주세요」₩2,000',
    ],
    review_summary: {
      pros: ['海鮮品質新鮮，釜山直送', '帝王蟹份量大、值回票價', '空間寬敞，氣氛好'],
      cons: ['帝王蟹為市價，費用不固定可能偏高', '週末需提前訂位', '辣鍋類小孩不適合，要注意點餐'],
    },
    opening_hours: { mon: '12:00-22:00', tue: '12:00-22:00', wed: '12:00-22:00', thu: '12:00-22:00', fri: '12:00-23:00', sat: '11:00-23:00', sun: '11:00-22:00' },
    tips: ['Day 3（4/3）晚餐，包車回來後前往'],
    tags: ['海鮮', '帝王蟹', '海雲台', 'Day3', '4/3'],
    rating: 4.5,
    review_count: 1240,
  },

  {
    id: 'r3',
    slug: 'haemok-michelin-eel',
    name_ko: '해목',
    name_zh: '海木（米其林鰻魚）',
    name_en: 'Haemok',
    type: 'restaurant',
    description: '釜山米其林推薦鰻魚專門店，炭火慢烤鮮活鰻魚，皮脆肉嫩，是整趟旅程最完美的收尾晚餐。',
    address_ko: '부산 해운대구 해운대시장 일대',
    address_zh: '釜山海雲台區海雲台市場一帶',
    district: '海雲台',
    city: '釜山',
    lat: 35.1630,
    lng: 129.1600,
    image_url: 'https://images.unsplash.com/photo-1534482421-64566f976cfa?w=800&q=80',
    price_range: 'expensive',
    avg_price_krw: 55000,
    spice_level: 'none',
    cuisine_type: ['鰻魚', '米其林'],
    kid_friendly_score: 3,
    kid_friendly_notes: '鰻魚本身無辣，小孩可吃。鰻魚飯（장어덮밥）特別適合小孩。需幫小孩去骨。',
    has_english_menu: false,
    accepts_card: true,
    reservation_required: true,
    reservation_links: [
      {
        platform: 'Catch Table',
        url: 'https://www.catchtable.net/',
        label: 'Catch Table Global 訂位',
        note: 'App 開啟後搜尋「해목」，旺季建議提前 2 週',
      },
      {
        platform: 'Tabling',
        url: 'https://www.tabling.co.kr/restaurant/2124',
        label: 'Tabling 線上候位',
        note: '可遠端加入候位，減少現場等待',
      },
    ],
    staff_phrases: [
      { situation: '我們幾個人（例：4人）', korean: '네 명이요' },
      { situation: '幫小孩把鰻魚去骨', korean: '아이 거 뼈 발라 주세요' },
      { situation: '小孩要吃鰻魚飯', korean: '장어덮밥 주세요' },
      { situation: '不要辣', korean: '안 맵게 해 주세요' },
      { situation: '要一杯水', korean: '물 주세요' },
      { situation: '有嬰兒椅嗎？', korean: '아기 의자 있어요?' },
      { situation: '結帳', korean: '계산해 주세요' },
    ],
    recommended_dishes: [
      { name_ko: '장어구이', name_zh: '烤鰻魚', price_krw: 55000, description: '招牌！炭火慢烤，皮脆肉嫩，無辣', must_order: true },
      { name_ko: '장어덮밥', name_zh: '鰻魚飯', price_krw: 22000, description: '蒲燒鰻魚蓋飯，甜醬入飯，小孩最愛', must_order: true },
      { name_ko: '장어탕', name_zh: '鰻魚湯', price_krw: 18000, description: '清湯，暖胃補身，無辣', must_order: false },
    ],
    ordering_tips: [
      '告知幾人用餐，鰻魚按「條」計價',
      '幫小孩點鰻魚飯（장어덮밥）最方便',
      '幫小孩去骨說「뼈 발라주세요」',
    ],
    review_summary: {
      pros: ['米其林水準，鰻魚鮮度與火候俱佳', '師傅在桌邊烤，是一種用餐體驗', '無辣，各年齡都能接受'],
      cons: ['價位偏高，人均約台幣1,200起', '需提前訂位，旺季難訂', '停車不方便'],
    },
    opening_hours: { mon: '11:30-21:30', tue: '11:30-21:30', wed: '11:30-21:30', thu: '11:30-21:30', fri: '11:30-21:30', sat: '11:30-21:30', sun: '11:30-21:30', note: '售完即止' },
    tips: ['Day 5 最後一天壓軸晚餐', '米其林推薦，用最完美的方式結束旅程'],
    tags: ['米其林', '鰻魚', '海雲台', 'Day5', '最後一天'],
    rating: 4.8,
    review_count: 560,
  },

  // ══════════════════════════════════════════════════════
  // 親子友善餐廳（2-6歲）
  // ══════════════════════════════════════════════════════

  {
    id: 'r6',
    slug: 'matchandeul-haeundae',
    name_ko: '맛찬들왕소금구이 해운대점',
    name_zh: '맛찬들 鹽烤豬肉 海雲台店',
    name_en: 'Matchandeul Haeundae',
    type: 'restaurant',
    description: '맛찬들連鎖海雲台分店，住在海雲台時步行可達。鹽烤豬五花無辣，帶小孩用餐最放心，性價比高。',
    address_ko: '부산 해운대구 해운대로',
    address_zh: '釜山海雲台區海雲台路（海雲台站附近）',
    district: '海雲台',
    city: '釜山',
    lat: 35.1628,
    lng: 129.1637,
    image_url: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800&q=80',
    price_range: 'moderate',
    avg_price_krw: 18000,
    spice_level: 'none',
    cuisine_type: ['韓式烤肉', '豬五花'],
    kid_friendly_score: 5,
    kid_friendly_notes: '同西面店，完全無辣，帶小孩非常適合。',
    min_age: 1,
    has_english_menu: false,
    accepts_card: true,
    reservation_required: false,
    reservation_links: [
      {
        platform: 'Catch Table',
        url: 'https://www.catchtable.net/',
        label: 'Catch Table Global 查看',
        note: 'App 開啟後搜尋「맛찬들왕소금구이 해운대」',
      },
    ],
    staff_phrases: [
      { situation: '我們幾個人（例：4人）', korean: '네 명이요' },
      { situation: '幫小孩把肉剪小塊', korean: '아이 거 작게 잘라 주세요' },
      { situation: '加點蒸蛋', korean: '계란찜 주세요' },
      { situation: '加點飯', korean: '공기밥 주세요' },
      { situation: '要一杯水', korean: '물 주세요' },
      { situation: '有嬰兒椅嗎？', korean: '아기 의자 있어요?' },
      { situation: '結帳', korean: '계산해 주세요' },
    ],
    recommended_dishes: [
      { name_ko: '왕소금구이', name_zh: '鹽烤豬五花', price_krw: 14000, description: '無辣，炭烤酥脆，小孩首選', must_order: true },
      { name_ko: '계란찜', name_zh: '蒸蛋', price_krw: 2000, description: '軟嫩蒸蛋，小孩必點', must_order: true },
    ],
    ordering_tips: ['同西面店點法，幫小孩剪肉說「작게 잘라주세요」'],
    review_summary: {
      pros: ['住海雲台時步行可達，最方便', '品質和西面店一樣穩定', '適合有小孩的家庭'],
      cons: ['同樣需要等候', '份量固定，帶1-2個小孩可能點太多'],
    },
    opening_hours: { mon: '11:30-23:00', tue: '11:30-23:00', wed: '11:30-23:00', thu: '11:30-23:00', fri: '11:30-23:00', sat: '11:30-23:00', sun: '11:30-23:00' },
    tips: ['住海雲台時的最佳親子晚餐選擇'],
    tags: ['豬五花', '無辣', '親子', '海雲台'],
    rating: 4.6,
    review_count: 1500,
  },

  // ══════════════════════════════════════════════════════
  // 親子友善景點
  // ══════════════════════════════════════════════════════

  {
    id: 'a1',
    slug: 'sealife-busan-aquarium',
    name_ko: '씨라이프 부산아쿠아리움',
    name_zh: 'SEA LIFE 釜山水族館',
    name_en: 'SEA LIFE Busan Aquarium',
    type: 'attraction',
    description: '海雲台海灘旁的人氣水族館，3萬5千多隻海洋生物、鯊魚隧道步道、企鵝表演，是帶2-6歲小孩最棒的室內景點。冷氣充足，雨天必去。',
    address_ko: '부산 해운대구 해운대해변로 266',
    address_zh: '釜山海雲台區海雲台海邊路266號',
    district: '海雲台',
    city: '釜山',
    lat: 35.1582,
    lng: 129.1598,
    image_url: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=800&q=80',
    price_range: 'moderate',
    ticket_price_krw: 31000,
    ticket_price_free: false,
    booking_url: 'https://www.visitsealife.com/busan/en/tickets-passes/',
    time_needed_minutes: 120,
    best_time_to_visit: '平日上午10-12點，人最少',
    kid_friendly_score: 5,
    kid_friendly_notes: '36個月以下免費（需出示證件）。鯊魚隧道讓2歲小孩也會超興奮。全館有電梯，推車友善。韓國多個親子旅遊部落客列為釜山親子首選。',
    min_age: 0,
    reservation_links: [
      {
        platform: 'Official',
        url: 'https://www.visitsealife.com/busan/en/tickets-passes/',
        label: '官網購票（最多省30%）',
        note: '線上購票直接掃QR入場，不用排隊',
      },
      {
        platform: 'KKday',
        url: 'https://www.kkday.com/en-us/product/2880-sea-life-busan-aquarium-tickets-korea',
        label: 'KKday 購票',
      },
      {
        platform: 'Klook',
        url: 'https://www.klook.com/en-US/activity/1251-sea-life-aquarium-busan/',
        label: 'Klook 購票',
      },
    ],
    review_summary: {
      pros: ['鯊魚隧道是小孩最驚喜的體驗，3歲也會目瞪口呆', '36個月以下免費，減輕費用壓力', '冷氣舒適，夏天雨天都適合', '企鵝、水獺、水母展區讓小孩流連忘返'],
      cons: ['週末和假日排隊長，建議提前網購跳過人龍', '部分展示區有些昏暗，2歲幼兒可能緊張', '館內餐廳選擇少，建議前後到外面吃飯', '票價不含特別表演，需另外確認'],
    },
    opening_hours: { mon: '10:00-19:00', tue: '10:00-19:00', wed: '10:00-19:00', thu: '10:00-19:00', fri: '10:00-19:00', sat: '10:00-20:00', sun: '10:00-20:00', note: '最後入場比閉館早1小時' },
    tips: [
      '網購比現場最多省30%！',
      '3歲以下帶出生證明可免費入場',
      '從海雲台站步行5分鐘，與海灘可以合併一天行程',
    ],
    tags: ['水族館', '鯊魚', '室內', '雨天', '親子', '海雲台', '必去'],
    rating: 4.5,
    review_count: 8900,
  },

  {
    id: 'a2',
    slug: 'national-maritime-museum',
    name_ko: '국립해양박물관',
    name_zh: '國立海洋博物館',
    name_en: 'National Maritime Museum of Korea',
    type: 'attraction',
    description: '完全免費的海洋博物館，館內有專為5歲以下設計的「섬마을 놀이터（島村遊樂場）」、兒童博物館、小型水族館，可停留2-3小時，是最佳免費親子景點。',
    address_ko: '부산 영도구 해양로301번길 45',
    address_zh: '釜山影島區海洋路301巷45號',
    district: '影島',
    city: '釜山',
    lat: 35.0810,
    lng: 129.0724,
    image_url: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80',
    price_range: 'free',
    ticket_price_free: true,
    time_needed_minutes: 150,
    best_time_to_visit: '平日上午，人少設施都能玩到',
    kid_friendly_score: 5,
    kid_friendly_notes: '2樓兒童博物館和「섬마을 놀이터」是專為幼兒設計的互動區，需1名大人陪同入場。全館電梯，推車可通行。館內有咖啡廳。',
    min_age: 1,
    reservation_links: [
      {
        platform: 'Official',
        url: 'https://www.mmk.or.kr/mobile/eng/?folder=exhibition&page=kids',
        label: '官網查看兒童展覽資訊',
      },
    ],
    review_summary: {
      pros: ['完全免費，是釜山最超值的親子景點', '幼兒互動遊樂場專為5歲以下設計', '館內有免費小型水族館', '全館推車可通行，電梯完善'],
      cons: ['週一休館，出發前務必確認', '影島位置稍遠，需搭計程車或公車', '主要海洋歷史展區對幼兒吸引力較低，專注去兒童區即可', '部分說明牌以韓文為主'],
    },
    opening_hours: { tue: '09:00-18:00', wed: '09:00-18:00', thu: '09:00-18:00', fri: '09:00-18:00', sat: '09:00-21:00', sun: '09:00-19:00', note: '週一公休，新年、春節、中秋休館' },
    tips: ['週一休館，行程安排要注意', '從南浦洞搭計程車約15分鐘，₩8,000左右', '免費小型水族館在館內'],
    tags: ['免費', '博物館', '幼兒', '室內', '雨天', '影島', '推車友善'],
    rating: 4.6,
    review_count: 3400,
  },

  {
    id: 'a3',
    slug: 'blueline-park',
    name_ko: '해운대 블루라인파크',
    name_zh: '海雲台藍線公園（天空膠囊 + 海灘小火車）',
    name_en: 'Haeundae Blueline Park',
    type: 'attraction',
    description: '沿海岸舊鐵道改建的觀光路線，分「天空膠囊（4人艙）」和「海灘小火車」。全程4.8公里欣賞東海海景。帶小孩建議搭海灘小火車更舒適安全。',
    address_ko: '부산 해운대구 달맞이길 62번길 11 (미포정류장)',
    address_zh: '釜山海雲台區迎月路62巷11號（尾浦乘車站）',
    district: '海雲台',
    city: '釜山',
    lat: 35.1627,
    lng: 129.1715,
    image_url: 'https://images.unsplash.com/photo-1501594907352-04cda38ebc29?w=800&q=80',
    price_range: 'moderate',
    ticket_price_krw: 8000,
    ticket_price_free: false,
    booking_url: 'https://www.bluelinepark.com/eng/booking.do',
    time_needed_minutes: 90,
    best_time_to_visit: '晴天早上9-11點，光線最美',
    kid_friendly_score: 4,
    kid_friendly_notes: '36個月以下免費。帶幼兒強烈推薦「海灘小火車」而非天空膠囊：空間寬敞、通風、沒有密閉感，且可以在各站下車。天空膠囊夏天無冷氣、密閉空間可能讓幼兒不舒服。',
    min_age: 0,
    reservation_links: [
      {
        platform: 'Official',
        url: 'https://www.bluelinepark.com/eng/booking.do',
        label: '官網訂票（建議提前）',
        note: '天空膠囊週末秒殺，需提前訂；小火車現場排隊購票即可',
      },
      {
        platform: 'KKday',
        url: 'https://www.kkday.com/en-us/product/123012-haeundae-blueline-park-beach-train-sky-capsule-ticket-korea',
        label: 'KKday 購票',
      },
    ],
    review_summary: {
      pros: ['沿海岸鐵道的景觀獨一無二，照片超美', '海灘小火車空間寬敞，帶小孩輕鬆', '36個月以下免費', '天空膠囊4人共享，拍照體驗感佳'],
      cons: ['天空膠囊夏天無冷氣，密閉悶熱不適合幼兒', '天空膠囊週末很難訂，需提前幾週', '海灘小火車現場購票可能等候', '折返需搭同方向，規劃時間要預留'],
    },
    opening_hours: { mon: '09:00-17:30', tue: '09:00-17:30', wed: '09:00-17:30', thu: '09:00-17:30', fri: '09:00-17:30', sat: '09:00-17:30', sun: '09:00-17:30', note: '天空膠囊每次週二開放4週後的預約' },
    tips: [
      '帶幼兒首選海灘小火車（해변열차），票價₩8,000-10,000',
      '天空膠囊（스카이캡슐）₩30,000/艙，適合大人或較大孩子',
      '尾浦站（미포정류장）在海雲台海灘東端步行5分鐘',
    ],
    tags: ['海景', '觀光', '火車', '膠囊', '海雲台', '親子', '特色體驗'],
    rating: 4.6,
    review_count: 6200,
  },

  {
    id: 'a4',
    slug: 'lotte-world-busan',
    name_ko: '롯데월드 어드벤처 부산',
    name_zh: '樂天世界冒險 釜山',
    name_en: 'Lotte World Adventure Busan',
    type: 'attraction',
    description: '釜山唯一主題樂園（2022年開幕），設有幼兒專區「歡樂牧場」6項適合2-6歲的遊樂設施：餅乾小火車、旋轉木馬、小農場等，是釜山親子一日遊的熱門選擇。',
    address_ko: '부산 기장군 기장읍 동부산관광로 42',
    address_zh: '釜山機張郡機張邑東釜山觀光路42號',
    district: '機張',
    city: '釜山',
    lat: 35.2285,
    lng: 129.2234,
    image_url: 'https://images.unsplash.com/photo-1513889961551-628c1e5e2ee9?w=800&q=80',
    price_range: 'expensive',
    ticket_price_krw: 33000,
    ticket_price_free: false,
    booking_url: 'https://adventure.lotteworld.com/eng/',
    time_needed_minutes: 360,
    best_time_to_visit: '平日開門（10點）就進，幼兒區幾乎沒排隊',
    kid_friendly_score: 4,
    kid_friendly_notes: '「歡樂牧場」幼兒專區有6項無身高限制的設施，2歲就可以玩。36個月以下₩12,000（低收費入場）。室內外混合，冷熱天都有去處。',
    min_age: 1,
    reservation_links: [
      {
        platform: 'Official',
        url: 'https://adventure.lotteworld.com/eng/price/gstt/information/list.do',
        label: '官網購票',
      },
      {
        platform: 'KKday',
        url: 'https://www.kkday.com/en/product/19296-busan-lotte-world-adventure-tickets-korea',
        label: 'KKday 購票（可享優惠）',
      },
      {
        platform: 'Klook',
        url: 'https://www.klook.com/en-US/activity/75094-lotte-world-busan/',
        label: 'Klook 購票',
      },
    ],
    review_summary: {
      pros: ['釜山唯一主題樂園，有獨特性', '幼兒專區設施專為小孩設計，無身高限制', '冬天有室內設施可避寒', '有豐富餐飲選擇，解決吃飯問題'],
      cons: ['位於機張，離海雲台30-40分鐘車程', '僅有幼兒的家庭，可玩設施有限，票價偏貴', '熱門設施週末排隊長，帶幼兒體力消耗大', '嬰兒車可借用但數量有限'],
    },
    opening_hours: { mon: '10:00-20:00', tue: '10:00-20:00', wed: '10:00-20:00', thu: '10:00-20:00', fri: '10:00-20:00', sat: '10:00-21:00', sun: '10:00-21:00' },
    tips: [
      '兒童（3-12歲）₩33,000，36個月以下₩12,000',
      'KKday / Klook 購票通常有9折優惠',
      '幼兒專區「즐거운 목장」在入場後左手邊',
      '從海雲台搭計程車約₩30,000，30-40分鐘',
    ],
    tags: ['主題樂園', '幼兒設施', '室內', '一日遊', '機張', '親子'],
    rating: 4.3,
    review_count: 4700,
  },

  // ══════════════════════════════════════════════════════
  // 購物 / 折扣資訊
  // ══════════════════════════════════════════════════════

  {
    id: 's1',
    slug: 'shinsegae-centum-city',
    name_ko: '신세계백화점 센텀시티점',
    name_zh: '新世界百貨 Centum City（全球最大百貨）',
    name_en: 'Shinsegae Centum City',
    type: 'shopping',
    description: '金氏世界紀錄認定的全球最大百貨公司，館內有 KidZania、Spa Land、溜冰場、電影院、屋頂主題公園。外國旅客可到B1外國顧客服務台領取專屬折扣券！',
    address_ko: '부산 해운대구 센텀남대로 35',
    address_zh: '釜山海雲台區Centum南大路35號',
    district: '海雲台',
    city: '釜山',
    lat: 35.1688,
    lng: 129.1308,
    image_url: 'https://images.unsplash.com/photo-1441984904996-e0b6ba687e04?w=800&q=80',
    price_range: 'moderate',
    kid_friendly_score: 4,
    kid_friendly_notes: '館內有 KidZania（3歲以上，需另買票）、屋頂主題公園、溜冰場。全館推車友善，電梯完善。外國旅客可在B1服務台領取外國人專屬折扣券。',
    time_needed_minutes: 240,
    reservation_links: [
      {
        platform: 'Official',
        url: 'https://english.visitkorea.or.kr/svc/contents/contentsView.do?vcontsId=217965',
        label: '外國旅客折扣券說明',
        note: '持護照至B1外國顧客服務台領取，現場兌換',
      },
      {
        platform: 'KKday',
        url: 'https://www.kkday.com/en/product/35042-kidzania-busan-tickets-korea',
        label: 'KKday 購買 KidZania 門票',
      },
    ],
    staff_phrases: [
      { situation: '請問外國旅客服務台在哪裡？', korean: '외국인 서비스 데스크 어디 있어요?' },
      { situation: '可以退稅嗎？（出示護照）', korean: '세금 환급 해주세요. (여권 드릴게요)' },
      { situation: '6樓兒童樓層怎麼去？', korean: '6층 아동관 어떻게 가요?' },
      { situation: '有沒有2歲穿的尺寸？', korean: '두 살 입는 사이즈 있어요?' },
      { situation: '有更小的尺寸嗎？', korean: '더 작은 사이즈 있어요?' },
      { situation: '可以換貨嗎？', korean: '교환 가능해요?' },
      { situation: '請給我一個購物袋', korean: '쇼핑백 주세요' },
    ],
    review_summary: {
      pros: ['6樓整層兒童館，Nike Kids / Etoi / Baby Dior 等品牌一次買齊', '外國旅客B1服務台有專屬折扣券（₩10,000優惠）和即時退稅', 'KidZania 在館內，親子購物一條龍', '全館推車友善，電梯完善，地鐵直達'],
      cons: ['面積太大容易迷路，建議先看地圖', '週末人潮洶湧，帶幼兒較吃力', 'KidZania 需另購票，排隊等候長', '每月第4個週一公休'],
    },
    opening_hours: { mon: '10:30-20:00', tue: '10:30-20:00', wed: '10:30-20:00', thu: '10:30-20:00', fri: '10:30-20:30', sat: '10:30-20:30', sun: '10:30-20:30', note: '每月第4個週一公休；餐廳區通常延長至21:00' },
    tips: [
      '🎫 外國旅客必去B1「외국인 고객 서비스 데스크」領取折扣券！',
      '👶 6樓兒童館：Nike Kids、New Balance Kids、Etoi（3-7歲）、Baby Dior 等',
      '💰 出示護照即時退稅（VAT 約4-7%）',
      '🚇 地鐵2號線 Centum City 站地下直通',
    ],
    tags: ['購物', '兒童館', '折扣', '退稅', 'KidZania', '全球最大', '海雲台', '童裝'],
    rating: 4.5,
    review_count: 12000,
  },

  {
    id: 's2',
    slug: 'visit-busan-pass',
    name_ko: '비짓부산패스',
    name_zh: 'Visit Busan Pass（外國人專屬旅遊卡）',
    name_en: 'Visit Busan Pass',
    type: 'shopping',
    description: '釜山外國旅客專屬旅遊卡，一張卡涵蓋40+景點免費入場（含水族館、SpaLand、海灘小火車等）+160+餐廳購物折扣。24小時卡₩49,000，省超多！',
    address_ko: '부산 전역 (온라인 구매)',
    address_zh: '釜山全區通用（線上購買）',
    district: '全釜山',
    city: '釜山',
    lat: 35.1796,
    lng: 129.0756,
    image_url: 'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=800&q=80',
    price_range: 'moderate',
    ticket_price_krw: 49000,
    ticket_price_free: false,
    booking_url: 'https://www.visitbusanpass.com/',
    time_needed_minutes: 0,
    kid_friendly_score: 5,
    kid_friendly_notes: '包含SEA LIFE水族館、海灘小火車、SpaLand等親子景點，外國人專屬，持護照購買。建議一天密集玩景點時使用，效益最大。',
    reservation_links: [
      {
        platform: 'Official',
        url: 'https://www.visitbusanpass.com/',
        label: '官網購買 Visit Busan Pass',
      },
      {
        platform: 'Klook',
        url: 'https://www.klook.com/en-US/activity/81576-visit-busan-pass/',
        label: 'Klook 購買',
      },
      {
        platform: 'KKday',
        url: 'https://www.kkday.com/en/product/145568-visit-busan-pass',
        label: 'KKday 購買',
      },
    ],
    review_summary: {
      pros: ['涵蓋景點多，安排密集時非常划算', 'SEA LIFE + 海灘小火車 + SpaLand 三個加起來就回本', '使用方便，手機掃QR入場', '外國人專屬，韓國人不能買'],
      cons: ['24小時計時從第一個使用景點開始，需集中使用', '部分熱門景點仍需另外預約（如天空膠囊）', '部分景點淡季或暫停無法使用，建議出發前確認', '需有網路才能使用手機版'],
    },
    opening_hours: { note: '線上購買，6個月內啟用有效，啟用後24/48小時有效' },
    tips: [
      '💡 含SEA LIFE(₩31,000) + 藍線公園小火車(₩10,000) + SpaLand(₩18,000) = ₩59,000，24H卡₩49,000 直接省錢！',
      '📱 購買後下載到手機，掃QR進場',
      '🎯 安排景點集中的那天使用效益最大',
    ],
    tags: ['旅遊卡', '折扣', '外國人', '省錢', '必買', '含景點'],
    rating: 4.4,
    review_count: 2100,
  },

  // ══════════════════════════════════════════════════════
  // 釜山豬肉湯飯（돼지국밥）
  // ══════════════════════════════════════════════════════

  {
    id: 'g1',
    slug: 'miryang-soondae-gukbap',
    name_ko: '밀양순대돼지국밥 부산본점',
    name_zh: '密陽純大豬肉湯飯 釜山本店',
    name_en: 'Miryang Soondae Dwaeji Gukbap',
    type: 'restaurant',
    description: '海雲台最人氣豬肉湯飯，24小時不打烊。雪白濃郁豬骨湯無腥味，辣醬另外盛放，可請店員準備幼兒專用無辣清湯。藝人임영웅（任英雄）光顧5次後爆紅，現為釜山親子必吃。',
    address_ko: '부산 해운대구 구남로 28',
    address_zh: '釜山海雲台區九南路28號',
    district: '海雲台',
    city: '釜山',
    lat: 35.1630,
    lng: 129.1632,
    image_url: 'https://images.unsplash.com/photo-1547592180-85f173990554?w=800&q=80',
    price_range: 'budget',
    avg_price_krw: 11000,
    spice_level: 'none',
    cuisine_type: ['豬肉湯飯', '釜山料理', '순대'],
    kid_friendly_score: 5,
    kid_friendly_notes: '可請店員準備「아기 국물」（幼兒湯），單獨盛放清湯不加辣醬，2歲幼兒也能喝。辣醬（다대기）全程自行添加，小孩的碗完全無辣。24H營業解決帶孩子出門時間不固定的問題。',
    min_age: 0,
    has_english_menu: false,
    accepts_card: true,
    reservation_required: false,
    reservation_links: [
      {
        platform: 'Catch Table',
        url: 'https://www.catchtable.net/',
        label: 'Catch Table Global 查看',
        note: 'App 開啟後搜尋「밀양순대돼지국밥 해운대」',
      },
      {
        platform: 'AutoReserve',
        url: 'https://autoreserve.com/ko/restaurants/UHu5bzwZwBP5vTSyktbo',
        label: '線上等位（AutoReserve）',
        note: '可線上加入候位，不用現場枯等',
      },
      {
        platform: 'Tabling',
        url: 'https://www.tabling.co.kr/place/677cc8ec66de5f069877e8ae',
        label: 'Tabling 線上候位',
        note: '遠端候位，到海雲台附近再去取號',
      },
    ],
    staff_phrases: [
      { situation: '我們幾個人（例：4人）', korean: '네 명이요' },
      { situation: '幫小孩準備無辣幼兒清湯', korean: '아기 국물 따로 주세요' },
      { situation: '辣醬請分開放（不要加進去）', korean: '다대기 따로 주세요' },
      { situation: '追加一碗飯', korean: '공기밥 주세요' },
      { situation: '湯可以再加嗎？', korean: '국물 더 주세요' },
      { situation: '要一杯水', korean: '물 주세요' },
      { situation: '有嬰兒椅嗎？', korean: '아기 의자 있어요?' },
      { situation: '結帳', korean: '계산해 주세요' },
    ],
    recommended_dishes: [
      { name_ko: '돼지국밥', name_zh: '豬肉湯飯', price_krw: 10000, description: '雪白豬骨濃湯，辣醬另上，小孩碗完全無辣', must_order: true },
      { name_ko: '순대국밥', name_zh: '純大湯飯', price_krw: 10000, description: '加入韓式血腸，成人推薦，口感豐富', must_order: false },
      { name_ko: '수육백반', name_zh: '水肉套餐', price_krw: 13000, description: '白切豬肉 + 湯 + 飯，肉質軟嫩小孩好咬', must_order: true },
    ],
    ordering_tips: [
      '幫小孩點「아기 국물 따로 주세요」（幼兒清湯另外盛）',
      '辣醬（다대기）自行添加，不加就是完全無辣',
      '米飯份量小，追加說「공기밥 주세요」₩1,000',
      '泡菜、蘿蔔泡菜、韭菜沙拉可自取免費補充',
    ],
    review_summary: {
      pros: ['24小時營業全年無休，帶孩子出門時間彈性最適合', '明確提供幼兒專用無辣清湯，對親子最友善', '豬骨湯完全無腥味，外國人也容易接受', '海雲台鬧區，逛海灘後步行可達'],
      cons: ['米飯份量偏小，2大1小可能需追加', '觀光區位置，用餐時段人流多較吵鬧', '知名度高人氣旺，尖峰時段需等候', '部分老饕認為湯頭偏清淡，不如傳統老店濃郁'],
    },
    opening_hours: { note: '24小時營業，全年無休（연중무휴）' },
    tips: [
      '全釜山豬肉湯飯中對親子最友善，是帶幼兒的首選',
      '住海雲台時，任何時間點都可以去，超方便',
      '海雲台站步行約5分鐘',
    ],
    tags: ['豬肉湯飯', '24H', '無辣', '幼兒友善', '釜山料理', '海雲台', '必吃'],
    rating: 4.3,
    review_count: 2800,
  },

  // ══════════════════════════════════════════════════════
  // 兒童購物（K 系列）
  // ══════════════════════════════════════════════════════

  {
    id: 'k2',
    slug: 'lotte-premium-outlet-dongbusan',
    name_ko: '롯데 프리미엄 아울렛 동부산점',
    name_zh: '樂天 Premium Outlet 東釜山店',
    name_en: 'Lotte Premium Outlet Dongbusan',
    type: 'shopping',
    description: '東釜山複合購物中心，與樂天世界釜山同址，集結MLB Kids、NIKE Kids、Polo Ralph Lauren Kids 等品牌童裝，Outlet折扣加上韓國定價，是買高品質童裝最划算的地點。',
    address_ko: '부산 기장군 기장읍 동부산관광6로 59 롯데 프리미엄 아울렛 동부산점',
    address_zh: '釜山機張郡機張邑東釜山觀光6路59號 樂天Premium Outlet東釜山店',
    district: '機張',
    city: '釜山',
    lat: 35.2417,
    lng: 129.2218,
    image_url: 'https://images.unsplash.com/photo-1567401893414-76b7b1e5a7a5?w=800&q=80',
    price_range: 'moderate',
    kid_friendly_score: 5,
    kid_friendly_notes: '戶外廣場有親子休憩區，嬰兒推車可借用，室內外均有哺乳室。可與隔壁樂天世界串聯成一日行程。',
    has_english_menu: false,
    accepts_card: true,
    ticket_price_free: false,
    staff_phrases: [
      { situation: '兒童服飾區在哪裡？', korean: '아동 의류 어디 있어요?' },
      { situation: 'MLB Kids 在哪裡？', korean: 'MLB 키즈 어디 있어요?' },
      { situation: '可以退稅嗎？（出示護照）', korean: '세금 환급 해주세요. (여권 드릴게요)' },
      { situation: '有沒有4歲穿的尺寸？', korean: '네 살 입는 사이즈 있어요?' },
      { situation: '有更小的尺寸嗎？', korean: '더 작은 사이즈 있어요?' },
      { situation: '可以換貨嗎？', korean: '교환 가능해요?' },
      { situation: '可以借推車嗎？', korean: '유모차 빌릴 수 있어요?' },
      { situation: '結帳', korean: '계산해 주세요' },
    ],
    opening_hours: { mon: '10:30-21:00', tue: '10:30-21:00', wed: '10:30-21:00', thu: '10:30-21:00', fri: '10:30-22:00', sat: '10:30-22:00', sun: '10:30-21:00', note: '週五六延長至22點' },
    tips: [
      '與樂天世界釜山同址，可同日串聯（先逛樂天世界，傍晚再逛Outlet）',
      'MLB Kids、Polo Kids 韓國定價比台灣便宜，Outlet再打折更划算',
      '購物滿₩30,000可辦即時退稅（TAX FREE），帶護照',
      '距海雲台車程約30分鐘，建議包車或開車前往',
      '設有哺乳室（수유실）與親子廁所，帶嬰兒非常方便',
    ],
    tags: ['童裝', '購物', '機張', 'MLB Kids', 'Nike Kids', 'Outlet', '樂天世界', '退稅'],
    review_summary: {
      pros: ['MLB Kids 等品牌童裝比台灣便宜20-30%', '可與樂天世界合併成全天行程', '停車場超大，自駕最方便', '設施齊全，哺乳室、嬰兒推車借用一應俱全'],
      cons: ['距市區較遠，需搭車30分鐘以上', '部分Outlet商品為過季款，尺寸較少', '假日停車場仍可能滿車，建議早到'],
    },
    rating: 4.4,
    review_count: 2100,
  },

  // ══════════════════════════════════════════════════════
  // 甜點/小吃店
  // ══════════════════════════════════════════════════════

  {
    id: 'd1',
    slug: 'horangi-jellatteok-haeundae',
    name_ko: '호랑이젤라떡 해운대',
    name_zh: '虎斑果凍餅 海雲台',
    name_en: 'Horangi Jellatteok Haeundae',
    type: 'dessert',
    description: '釜山代表性甜點店，以韌Q的糯米餅搭配滑軟果凍聞名。獨家原料拒絕加盟，累計銷售量可環遊地球一圈。7種基本口味每月推出新口味，是社群媒體上最火紅的釜山甜點。',
    address_ko: '부산 해운대구 달맞이길 60-2',
    address_zh: '釜山海雲台區達摩裏60-2號',
    district: '海雲台',
    city: '釜山',
    lat: 35.1585,
    lng: 129.1702,
    image_url: 'https://images.unsplash.com/photo-1551024506-0bccd828d307?w=800&q=80',
    price_range: 'moderate',
    avg_price_krw: 18000,
    spice_level: 'none',
    cuisine_type: ['韓式甜點', '果凍餅'],
    kid_friendly_score: 5,
    kid_friendly_notes: '完全無辣的甜點，小孩超愛。店內環境乾淨明亮，適合帶孩子。',
    has_english_menu: false,
    accepts_card: true,
    reservation_required: false,
    recommended_dishes: [
      { name_ko: '젤라떡 4개', name_zh: '果凍餅4個', price_krw: 18000, description: '經典組合，鹽奶油+餅乾+抹茶+開心果口味', must_order: true },
      { name_ko: '젤라떡 6개', name_zh: '果凍餅6個', price_krw: 25000, description: '加大份量，適合多人分享', must_order: false },
    ],
    ordering_tips: [
      '海邊步行1分鐘，買了直接帶到海灘吃',
      '每月新口味，建議關注IG查看',
      '外帶方便，適合打包回飯店',
    ],
    review_summary: {
      pros: ['釜山必吃甜點，社群媒體爆紅', '糯米餅韌Q+果凍滑軟的完美組合', '獨家配方，品質穩定', '海雲台海邊位置絕佳'],
      cons: ['假日排隊人多，需耐心等候', '價格偏高，一人份約NT$450', '部分口味需現場確認是否有貨'],
    },
    opening_hours: { mon: '12:00-21:00', tue: '12:00-21:00', wed: '12:00-21:00', thu: '12:00-21:00', fri: '12:00-21:00', sat: '12:00-21:00', sun: '12:00-21:00', note: '16:00-17:30休息' },
    tips: ['海雲台海灘旁，買了直接在海邊享用', 'IG觀看數破億，超夯甜點', '適合買來當伴手禮'],
    tags: ['甜點', '果凍餅', '海雲台', '社群熱門', '伴手禮'],
    rating: 4.8,
    review_count: 12500,
  },

  {
    id: 'd5',
    slug: 'onggi-jonggi-peanut-bread',
    name_ko: '옹기종기땅콩빵',
    name_zh: 'Onggi Jonggi 花生麵包',
    name_en: 'Onggi Jonggi Peanut Bread',
    type: 'dessert',
    description: '海雲台經典小吃，花生麵包專賣店。酥脆外層搭配香軟內層，高級花生香氣十足。40個₩5,000的親民價格，是最佳伴手禮選擇。海雲台必買，社群媒體上也相當熱門。',
    address_ko: '부산 해운대구 남천바다로29번길 35',
    address_zh: '釜山海雲台區南川海邊路29巷35號',
    district: '海雲台',
    city: '釜山',
    lat: 35.1560,
    lng: 129.1630,
    image_url: 'https://images.unsplash.com/photo-1558961363-fa8fdf82db35?w=800&q=80',
    price_range: 'budget',
    avg_price_krw: 5000,
    spice_level: 'none',
    cuisine_type: ['花生麵包', '韓式小吃'],
    kid_friendly_score: 5,
    kid_friendly_notes: '傳統韓式小吃，小孩愛吃。價格便宜，適合讓小孩多試幾種。',
    has_english_menu: false,
    accepts_card: true,
    reservation_required: false,
    recommended_dishes: [
      { name_ko: '땅콩빵 40개', name_zh: '花生麵包40個', price_krw: 5000, description: '經典份量，酥脆外層香軟內層', must_order: true },
      { name_ko: '땅콩빵 80개', name_zh: '花生麵包80個', price_krw: 10000, description: '加大包，適合多人或伴手禮', must_order: false },
    ],
    ordering_tips: [
      '海雲台必買伴手禮',
      '現烤熱騰騰最好吃',
      '適合買來當飛機零食',
    ],
    review_summary: {
      pros: ['海雲台經典小吃，社群推薦', '花生香氣十足，口感絕佳', '價格親民，一包約NT$125', '最適合伴手禮'],
      cons: ['假日人多，需排隊', '位置在海雲台稍偏', '需注意保存期限'],
    },
    opening_hours: { mon: '11:00-20:00', tue: '11:00-20:00', wed: '11:00-20:00', thu: '休息', fri: '11:00-22:00', sat: '10:00-22:00', sun: '10:00-22:00', note: '週四休息' },
    tips: ['海雲台逛街必買，花生麵包超夯', '最適合帶回台灣的伴手禮', '社群媒體上常被推薦'],
    tags: ['小吃', '花生麵包', '海雲台', '伴手禮', '社群熱門'],
    rating: 4.4,
    review_count: 2800,
  },
  {
    id: 'd6',
    slug: 'cu-honey-milk-twister',
    name_ko: 'CU 허니밀크 트위스터',
    name_zh: 'CU 蜂蜜牛奶軟霜',
    name_en: 'CU Honey Milk Twister',
    type: 'dessert',
    description: '2025 後半年爆紅的便利商店限定甜品，在 CU 便利商店線上社群大受歡迎，取名「杯中小奶油蛋糕」。軟霜質地綿密，搭配蜂蜜醬與碎黃金脆片，適合當快速補充小點心。',
    address_ko: 'CU 전국 매장',
    address_zh: 'CU 全國門市',
    district: '全釜山',
    city: '釜山',
    lat: 35.1796,
    lng: 129.0756,
    image_url: 'https://images.unsplash.com/photo-1532375810709-4812d5fddf75?w=800&q=80',
    price_range: 'budget',
    avg_price_krw: 2800,
    spice_level: 'none',
    cuisine_type: ['便利商店', '冷飲', '季節限定'],
    kid_friendly_score: 5,
    kid_friendly_notes: '完全無辣，奶香甜度適中，適合小孩分享。',
    has_english_menu: false,
    accepts_card: true,
    reservation_required: false,
    recommended_dishes: [
      { name_ko: '허니밀크 트위스터', name_zh: '蜂蜜牛奶軟霜', price_krw: 2800, description: '社群熱推甜點，綿密奶霜與蜂蜜脆片', must_order: true },
    ],
    ordering_tips: [
      'CU APP 有時會有買一送一優惠，出發前先查優惠券',
      '若當天門市缺貨，可試試鄰近門市',
      '冷凍櫃取出後稍放 1-2 分鐘口感最佳',
    ],
    review_summary: {
      pros: ['2025下半年社群爆紅新品', '甜度適中、口感像霜淇淋＋奶油蛋糕', '價格親民，超市隨買隨吃'],
      cons: ['夏天易化，建議盡快吃', '便利商店品項可能會迅速更替', '部分門市可能提早售罄'],
    },
    opening_hours: { note: 'CU 24小時營業（視門市而定）' },
    tips: ['方便旅途中補充甜點', '可買來冷藏後搭配咖啡當下午茶', '最新社群話題品項，必拍一張打卡'],
    tags: ['便利商店', '社群熱門', '季節限定', '零食', '冷飲'],
    rating: 4.5,
    review_count: 2200,
  },
  {
    id: 'd7',
    slug: 'gs25-cheese-bread-with-cocoa',
    name_ko: 'GS25 치즈브레드&코코아',
    name_zh: 'GS25 起司麵包＋可可冷飲',
    name_en: 'GS25 Cheese Bread & Cocoa',
    type: 'dessert',
    description: '2025 年社群人氣組合，GS25 便利商店的起司軟麵包限時套餐。外皮酥脆、裡層拉絲起司，配上可可冷飲容易拍出網美照，深受年輕旅客歡迎。',
    address_ko: 'GS25 전국 매장',
    address_zh: 'GS25 全國門市',
    district: '全釜山',
    city: '釜山',
    lat: 35.1796,
    lng: 129.0756,
    image_url: 'https://images.unsplash.com/photo-1512548425667-1002f01119f4?w=800&q=80',
    price_range: 'budget',
    avg_price_krw: 4500,
    spice_level: 'none',
    cuisine_type: ['便利商店', '麵包', '組合餐'],
    kid_friendly_score: 5,
    kid_friendly_notes: '無辣且起司濃郁，好入口。',
    has_english_menu: false,
    accepts_card: true,
    reservation_required: false,
    recommended_dishes: [
      { name_ko: '치즈브레드', name_zh: '起司麵包', price_krw: 3200, description: '拉絲起司內餡，餅皮微脆', must_order: true },
      { name_ko: '코코아', name_zh: '可可冷飲', price_krw: 1300, description: '甜而不膩的可可飲料', must_order: false },
    ],
    ordering_tips: [
      '先拍照再吃，社群爆紅必打卡',
      '如果店內沒貨可直接向店員詢問補貨',
      '搭地鐵站附近門市購買最方便',
    ],
    review_summary: {
      pros: ['便利商店就買到，超方便', '社群短影片爆紅，菜單搜尋度超高', '價格實惠，小孩也愛'],
      cons: ['有時限時販售，遇到沒貨', '糖分高，餐後適量', '可可易碎，外帶需小心'],
    },
    opening_hours: { note: 'GS25 24小時營業（視門市而定）' },
    tips: ['可作為行程間的小點心', '選連鎖大站門市比較穩定'],
    tags: ['便利商店', '社群熱門', '起司麵包', '可可飲', '小點心'],
    rating: 4.4,
    review_count: 1450,
  },

  // ══════════════════════════════════════════════════════
  // 行程景點（Day 2-5 活動）
  // ══════════════════════════════════════════════════════

  {
    id: 'act1',
    slug: 'gamcheon-hanbok-rental',
    name_ko: '의상대여 감천문화마을',
    name_zh: '甘川洞韓服體驗（衣裳貸與）',
    name_en: 'Gamcheon Culture Village Hanbok Rental',
    type: 'activity',
    description: '甘川洞文化村內的韓服租借店，穿上傳統韓服漫步五彩繽紛的小巷拍照打卡，是釜山最具代表性的文化體驗。小孩也有兒童韓服可選。',
    address_ko: '부산 사하구 감천동 감천문화마을',
    address_zh: '釜山沙下區甘川洞文化村',
    district: '西釜山',
    city: '釜山',
    lat: 35.0975,
    lng: 129.0106,
    image_url: 'https://images.unsplash.com/photo-1553621042-f6e147245754?w=800&q=80',
    price_range: 'moderate',
    avg_price_krw: 20000,
    time_needed_minutes: 120,
    kid_friendly_score: 4,
    kid_friendly_notes: '有兒童韓服可租借，小孩穿韓服拍照超可愛。巷弄有階梯，嬰兒推車較不方便，建議背巾。',
    review_summary: {
      pros: ['五彩村落拍照超美', '韓服體驗獨特有趣', '小孩穿韓服超可愛'],
      cons: ['階梯多，帶幼兒較累', '假日人潮擁擠', '停車不便，建議包車'],
    },
    opening_hours: { mon: '09:00-18:00', tue: '09:00-18:00', wed: '09:00-18:00', thu: '09:00-18:00', fri: '09:00-18:00', sat: '09:00-18:00', sun: '09:00-18:00' },
    tips: [
      'Google Maps: https://maps.app.goo.gl/ze2J3zzczsoJAQwQ8',
      '韓服租借約₩15,000-20,000/人，含髮飾',
      '建議上午去，光線好拍照漂亮',
    ],
    tags: ['韓服', '文化村', '拍照', '甘川洞', '西釜山', '體驗'],
    rating: 4.5,
    review_count: 5200,
  },

  {
    id: 'r7',
    slug: 'myeongseong-dakhanmari',
    name_ko: '명성닭한마리',
    name_zh: '明星一隻雞',
    name_en: 'Myeongseong Dakhanmari',
    type: 'restaurant',
    description: '人氣一隻雞鍋料理，整隻雞熬煮的濃郁高湯搭配年糕和馬鈴薯，湯頭鮮甜，可選不辣口味，適合全家享用的暖胃好選擇。',
    address_ko: '부산 사하구 감천동 일대',
    address_zh: '釜山沙下區（甘川洞附近）',
    district: '西釜山',
    city: '釜山',
    lat: 35.1010,
    lng: 129.0130,
    image_url: 'https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?w=800&q=80',
    price_range: 'moderate',
    avg_price_krw: 15000,
    spice_level: 'mild',
    cuisine_type: ['一隻雞', '雞湯鍋'],
    kid_friendly_score: 4,
    kid_friendly_notes: '雞湯底清淡鮮甜，可要求不辣。雞肉軟嫩好咬，年糕和馬鈴薯小孩都愛吃。',
    has_english_menu: false,
    accepts_card: true,
    reservation_required: false,
    staff_phrases: [
      { situation: '我們幾個人（例：4人）', korean: '네 명이요' },
      { situation: '不要辣', korean: '안 맵게 해 주세요' },
      { situation: '幫小孩把雞肉撕小塊', korean: '아이 거 작게 찢어 주세요' },
      { situation: '要一杯水', korean: '물 주세요' },
      { situation: '結帳', korean: '계산해 주세요' },
    ],
    recommended_dishes: [
      { name_ko: '닭한마리', name_zh: '一隻雞', price_krw: 28000, description: '招牌！整隻雞燉煮，湯頭鮮甜濃郁', must_order: true },
      { name_ko: '칼국수 사리', name_zh: '刀削麵加點', price_krw: 3000, description: '湯底煮麵，小孩最愛', must_order: true },
    ],
    ordering_tips: [
      '先喝湯、吃雞肉，最後下刀削麵（칼국수）收尾',
      '辣醬（다대기）另外放，不加就是無辣',
    ],
    review_summary: {
      pros: ['湯頭鮮甜，小孩也愛', '份量大，一鍋全家吃飽', '價格實惠'],
      cons: ['用餐時段需等候', '環境較傳統簡樸'],
    },
    opening_hours: { mon: '10:00-21:00', tue: '10:00-21:00', wed: '10:00-21:00', thu: '10:00-21:00', fri: '10:00-21:00', sat: '10:00-21:00', sun: '10:00-21:00' },
    tips: ['Day 2 午餐，甘川洞韓服體驗後步行前往'],
    tags: ['一隻雞', '雞湯', '午餐', '西釜山', '親子'],
    rating: 4.4,
    review_count: 1800,
  },

  {
    id: 'act2',
    slug: 'songdo-cable-car',
    name_ko: '송도 해상케이블카',
    name_zh: '松島海上纜車',
    name_en: 'Busan Air Cruise (Songdo Cable Car)',
    type: 'attraction',
    description: '韓國第一條海上纜車，全長1.62公里橫跨松島海灣，可選擇透明水晶車廂或一般車廂，俯瞰松島海灘與岩南公園的壯麗海景。',
    address_ko: '부산 서구 송도해변로 171',
    address_zh: '釜山西區松島海邊路171號',
    district: '西釜山',
    city: '釜山',
    lat: 35.0714,
    lng: 129.0147,
    image_url: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80',
    price_range: 'moderate',
    ticket_price_krw: 17000,
    ticket_price_free: false,
    time_needed_minutes: 60,
    best_time_to_visit: '晴天下午，海景最美',
    kid_friendly_score: 4,
    kid_friendly_notes: '一般車廂空間寬敞，帶小孩安全。水晶車廂（透明底）小小孩可能害怕，建議選一般車廂。36個月以下免費。',
    min_age: 0,
    reservation_links: [
      {
        platform: 'Official',
        url: 'https://www.busanaircruise.co.kr/',
        label: '官網購票',
      },
    ],
    review_summary: {
      pros: ['海上纜車視野壯麗', '水晶車廂拍照超美', '36個月以下免費'],
      cons: ['風大時可能暫停營運', '假日排隊長', '水晶車廂幼兒可能害怕'],
    },
    opening_hours: { mon: '09:00-21:00', tue: '09:00-21:00', wed: '09:00-21:00', thu: '09:00-21:00', fri: '09:00-22:00', sat: '09:00-22:00', sun: '09:00-21:00' },
    tips: [
      '一般車廂來回₩17,000，水晶車廂₩22,000',
      '帶幼兒建議選一般車廂，較安心',
      '從甘川洞包車約15分鐘可達',
    ],
    tags: ['纜車', '海景', '松島', '西釜山', '親子'],
    rating: 4.5,
    review_count: 4300,
  },

  {
    id: 'act4',
    slug: 'arte-museum-busan',
    name_ko: '아르떼뮤지엄 부산',
    name_zh: 'ARTE MUSEUM 釜山',
    name_en: 'ARTE MUSEUM Busan',
    type: 'attraction',
    description: '韓國最大的沉浸式數位藝術博物館，以光影投射、互動裝置打造出夢幻空間。花園、海洋、瀑布等主題區讓你走進畫中世界，超適合拍照。小孩也會被光影效果吸引。',
    address_ko: '부산 영도구 해양로247번길 29',
    address_zh: '釜山影島區海洋路247巷29號',
    district: '影島',
    city: '釜山',
    lat: 35.0785,
    lng: 129.0710,
    image_url: 'https://images.unsplash.com/photo-1554907984-15263bfd63bd?w=800&q=80',
    price_range: 'moderate',
    ticket_price_krw: 17000,
    ticket_price_free: false,
    time_needed_minutes: 90,
    best_time_to_visit: '平日下午，人少拍照不用排隊',
    kid_friendly_score: 4,
    kid_friendly_notes: '光影互動空間小孩會很興奮，適合各年齡層。室內有冷氣，推車可進入。部分暗場區域幼兒可能會怕。',
    min_age: 0,
    reservation_links: [
      {
        platform: 'Official',
        url: 'https://www.artemuseum.com/',
        label: '官網購票',
      },
    ],
    review_summary: {
      pros: ['沉浸式光影超夢幻，拍照爆美', '小孩被光影吸引會很開心', '室內有冷氣，雨天也適合', 'Google 4.9 星超高評價'],
      cons: ['假日人多影響拍照品質', '部分暗場區域幼兒可能害怕', '停留時間約1-1.5小時'],
    },
    opening_hours: { mon: '10:00-19:00', tue: '10:00-19:00', wed: '10:00-19:00', thu: '10:00-19:00', fri: '10:00-20:00', sat: '10:00-20:00', sun: '10:00-19:00', note: '最後入場比閉館早1小時' },
    tips: [
      'Google Maps: https://maps.app.goo.gl/jVyQhpHP14c5yrn28',
      'Day 2 下午松島纜車後包車前往',
      '建議提前網購門票，現場可能排隊',
    ],
    tags: ['沉浸式', '數位藝術', '拍照', '影島', '室內', '親子'],
    rating: 4.9,
    review_count: 2590,
  },

  {
    id: 'act8',
    slug: 'flipbook-studio-gamcheon',
    name_ko: '플립북 스튜디오 감천',
    name_zh: 'Flipbook Studio 甘川洞',
    name_en: 'Flipbook Studio Gamcheon',
    type: 'activity',
    description: '在甘川洞文化村拍攝翻頁動畫書（Flipbook），把旅行回憶製作成獨一無二的迷你翻頁動畫帶回家，是近年韓國超人氣的體驗活動。',
    address_ko: '부산 사하구 감천문화마을 일대',
    address_zh: '釜山沙下區甘川洞文化村內',
    district: '西釜山',
    city: '釜山',
    lat: 35.0978,
    lng: 129.0110,
    image_url: 'https://images.unsplash.com/photo-1492691527719-9d1e07e534b4?w=800&q=80',
    price_range: 'moderate',
    avg_price_krw: 15000,
    time_needed_minutes: 30,
    kid_friendly_score: 5,
    kid_friendly_notes: '拍攝過程有趣，小孩會覺得很好玩。成品是獨特的旅行紀念品。',
    review_summary: {
      pros: ['獨特的旅行紀念品', '拍攝過程有趣好玩', '小孩大人都喜歡'],
      cons: ['需等候製作時間', '熱門時段可能需排隊'],
    },
    opening_hours: { mon: '10:00-18:00', tue: '10:00-18:00', wed: '10:00-18:00', thu: '10:00-18:00', fri: '10:00-18:00', sat: '10:00-18:00', sun: '10:00-18:00' },
    tips: ['韓服體驗後順路造訪，穿韓服拍Flipbook更有紀念價值'],
    tags: ['體驗', '紀念品', '甘川洞', '西釜山', '拍照'],
    rating: 4.6,
    review_count: 950,
  },

  {
    id: 'c1',
    slug: 'p-ark-cafe-yeongdo',
    name_ko: 'P. ark',
    name_zh: 'P.ark 咖啡廳',
    name_en: 'P.ark Cafe',
    type: 'cafe',
    description: '影島 ARTE MUSEUM 附近的人氣咖啡廳，看完展覽後來這裡喝杯咖啡休息，環境舒適有設計感。',
    address_ko: '부산 영도구 해양로247번길 일대',
    address_zh: '釜山影島區海洋路247巷一帶',
    district: '影島',
    city: '釜山',
    lat: 35.0788,
    lng: 129.0715,
    image_url: 'https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=800&q=80',
    price_range: 'moderate',
    avg_price_krw: 7000,
    spice_level: 'none',
    cuisine_type: ['咖啡', '甜點'],
    kid_friendly_score: 4,
    kid_friendly_notes: '環境舒適，有兒童可喝的飲品。',
    has_english_menu: false,
    accepts_card: true,
    reservation_required: false,
    review_summary: {
      pros: ['ARTE MUSEUM 旁最佳休息站', '環境有設計感', '飲品品質好'],
      cons: ['假日可能客滿', '價格偏高'],
    },
    opening_hours: { mon: '10:00-20:00', tue: '10:00-20:00', wed: '10:00-20:00', thu: '10:00-20:00', fri: '10:00-21:00', sat: '10:00-21:00', sun: '10:00-20:00' },
    tips: ['ARTE MUSEUM 看完後步行即到，喝杯咖啡休息'],
    tags: ['咖啡廳', '影島', '休息', 'ARTE MUSEUM'],
    rating: 4.5,
    review_count: 680,
  },

  {
    id: 'r8',
    slug: 'haeundae-31cm-kalguksu',
    name_ko: '해운대31cm해물칼국수 해운대시장점',
    name_zh: '海雲台31cm海鮮刀削麵 海雲台市場店',
    name_en: 'Haeundae 31cm Haemul Kalguksu',
    type: 'restaurant',
    description: '海雲台市場內的人氣海鮮刀削麵，以超大份量海鮮和手工刀削麵聞名。湯頭鮮甜，海鮮料多實在，是海雲台在地人也愛吃的平價美食。',
    address_ko: '부산 해운대구 해운대시장 일대',
    address_zh: '釜山海雲台區海雲台市場',
    district: '海雲台',
    city: '釜山',
    lat: 35.1625,
    lng: 129.1635,
    image_url: 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=800&q=80',
    price_range: 'budget',
    avg_price_krw: 10000,
    spice_level: 'none',
    cuisine_type: ['刀削麵', '海鮮', '韓式'],
    kid_friendly_score: 4,
    kid_friendly_notes: '海鮮刀削麵湯頭清甜無辣，麵條軟Q小孩好吃。可請店員幫忙剪短麵條。',
    has_english_menu: false,
    accepts_card: true,
    reservation_required: false,
    staff_phrases: [
      { situation: '我們幾個人（例：4人）', korean: '네 명이요' },
      { situation: '幫小孩把麵剪短', korean: '아이 거 면 잘라 주세요' },
      { situation: '不要辣', korean: '안 맵게 해 주세요' },
      { situation: '要一杯水', korean: '물 주세요' },
      { situation: '結帳', korean: '계산해 주세요' },
    ],
    recommended_dishes: [
      { name_ko: '해물칼국수', name_zh: '海鮮刀削麵', price_krw: 10000, description: '招牌！滿滿海鮮配手工刀削麵，湯頭超鮮', must_order: true },
      { name_ko: '수육', name_zh: '水煮肉', price_krw: 20000, description: '白切豬肉，軟嫩無辣，配麵一起吃', must_order: false },
    ],
    ordering_tips: [
      '幫小孩剪麵說「면 잘라주세요」',
      '海鮮湯底本身無辣，非常適合小孩',
    ],
    review_summary: {
      pros: ['海鮮料多湯頭鮮甜', '價格便宜CP值高', '海雲台市場在地美食'],
      cons: ['用餐時段排隊', '座位較擁擠', '環境較傳統'],
    },
    opening_hours: { mon: '10:00-21:00', tue: '10:00-21:00', wed: '10:00-21:00', thu: '10:00-21:00', fri: '10:00-21:00', sat: '10:00-21:00', sun: '10:00-21:00' },
    tips: [
      'Google Maps: https://maps.app.goo.gl/vVJwzz8vMuJFTNK86',
      'Day 2 晚餐，包車回海雲台後步行前往',
      '海雲台市場內，很好找',
    ],
    tags: ['刀削麵', '海鮮', '平價', '海雲台', '市場'],
    rating: 4.5,
    review_count: 3100,
  },

  {
    id: 'p1',
    slug: 'daejeo-ecological-park',
    name_ko: '대저생태공원',
    name_zh: '大渚生態園區',
    name_en: 'Daejeo Ecological Park',
    type: 'park',
    description: '洛東江畔的大型生態公園，春天櫻花盛開時是釜山最美的賞櫻景點之一。園區內有自行車道，可租借腳踏車帶小孩沿河騎行，享受櫻花隧道美景。',
    address_ko: '부산 강서구 대저1동 2314-11',
    address_zh: '釜山江西區大渚1洞2314-11',
    district: '西釜山',
    city: '釜山',
    lat: 35.1477,
    lng: 128.9806,
    image_url: 'https://images.unsplash.com/photo-1522383225653-ed111181a951?w=800&q=80',
    price_range: 'free',
    ticket_price_free: true,
    time_needed_minutes: 150,
    best_time_to_visit: '3月底-4月初櫻花季，上午騎車最舒適',
    kid_friendly_score: 5,
    kid_friendly_notes: '平坦的自行車道非常適合帶小孩騎車，有親子協力車可租借。草地寬廣可讓小孩跑跳。',
    min_age: 0,
    review_summary: {
      pros: ['免費入場，櫻花季超美', '自行車道平坦，親子騎車安全', '草地寬廣，小孩可以自由跑跳', '4月初正值滿開'],
      cons: ['離市區較遠，需包車前往', '櫻花季人多', '廁所設施較簡陋'],
    },
    opening_hours: { note: '24小時開放（自行車租借約 09:00-18:00）' },
    tips: [
      'Google Maps: https://maps.app.goo.gl/JGAmpk9E2sozWUG47',
      '4月初櫻花滿開，是最佳造訪時間',
      '自行車租借約₩5,000-10,000/小時，有親子車',
      'Day 3 上午，包車前往',
    ],
    tags: ['賞櫻', '騎車', '公園', '免費', '西釜山', '親子', '春天'],
    rating: 4.6,
    review_count: 3200,
  },

  {
    id: 'act5',
    slug: 'skyline-luge-busan',
    name_ko: '스카이라인 루지 부산',
    name_zh: 'Skyline Luge 遛遛車',
    name_en: 'Skyline Luge Busan',
    type: 'activity',
    description: '從山坡上搭纜車上去，再乘坐無動力遛遛車滑下來，刺激又安全。有專用兒童車道，小孩和大人都能享受滑行樂趣，是釜山最受歡迎的親子活動之一。',
    address_ko: '부산 기장군 기장읍 기장해안로 205',
    address_zh: '釜山機張郡機張邑機張海岸路205號',
    district: '機張',
    city: '釜山',
    lat: 35.1860,
    lng: 129.2180,
    image_url: 'https://images.unsplash.com/photo-1596461404969-9ae70f2830c1?w=800&q=80',
    price_range: 'moderate',
    ticket_price_krw: 15000,
    ticket_price_free: false,
    time_needed_minutes: 90,
    best_time_to_visit: '平日上午，排隊最短',
    kid_friendly_score: 5,
    kid_friendly_notes: '110cm以上可單獨搭乘，110cm以下需與大人同乘。纜車上山＋遛遛車下山，小孩超興奮。',
    min_age: 2,
    reservation_links: [
      {
        platform: 'Official',
        url: 'https://www.skylineluge.com/busan/',
        label: '官網購票',
      },
      {
        platform: 'KKday',
        url: 'https://www.kkday.com/en/product/35045-skyline-luge-busan',
        label: 'KKday 購票',
      },
    ],
    review_summary: {
      pros: ['大人小孩都超愛，會想玩好幾次', '安全性高，有專用兒童車道', '海景纜車上山超美'],
      cons: ['假日排隊可達30-60分鐘', '夏天戶外偏熱', '離海雲台約20-30分鐘車程'],
    },
    opening_hours: { mon: '10:00-18:00', tue: '10:00-18:00', wed: '10:00-18:00', thu: '10:00-18:00', fri: '10:00-18:00', sat: '09:00-19:00', sun: '09:00-19:00' },
    tips: [
      '建議買2-3次票，小孩一定會想再玩',
      '110cm以下需與大人同乘',
      'Day 3 下午，大渚公園後包車前往',
    ],
    tags: ['遛遛車', 'Luge', '親子', '機張', '戶外', '必玩'],
    rating: 4.7,
    review_count: 5800,
  },

  {
    id: 'act6',
    slug: 'cheongsapo-skywalk',
    name_ko: '청사포 다릿돌 전망대',
    name_zh: '青沙浦天空步道',
    name_en: 'Cheongsapo Daritdol Observatory',
    type: 'attraction',
    description: '海上透明玻璃步道，延伸入海面上，腳下就是湛藍海水與岩石。免費入場，是海雲台近郊的人氣打卡景點，可搭配藍線公園膠囊列車一起遊覽。',
    address_ko: '부산 해운대구 청사포로 128',
    address_zh: '釜山海雲台區青沙浦路128號',
    district: '海雲台',
    city: '釜山',
    lat: 35.1569,
    lng: 129.1871,
    image_url: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&q=80',
    price_range: 'free',
    ticket_price_free: true,
    time_needed_minutes: 40,
    best_time_to_visit: '晴天上午，海水顏色最美',
    kid_friendly_score: 4,
    kid_friendly_notes: '透明玻璃步道小孩可能會緊張但也很興奮。有護欄安全。免費入場。',
    min_age: 0,
    review_summary: {
      pros: ['免費入場', '透明玻璃步道拍照超美', '可搭配膠囊列車一日遊'],
      cons: ['風大時步道可能關閉', '假日人多需排隊', '停留時間不長'],
    },
    opening_hours: { mon: '09:00-18:00', tue: '09:00-18:00', wed: '09:00-18:00', thu: '09:00-18:00', fri: '09:00-18:00', sat: '09:00-18:00', sun: '09:00-18:00', note: '天候不佳可能關閉' },
    tips: [
      'Day 4 搭膠囊列車後順路造訪',
      '免費景點，停留約30-40分鐘',
    ],
    tags: ['天空步道', '免費', '海景', '海雲台', '打卡'],
    rating: 4.4,
    review_count: 3600,
  },

  {
    id: 'act7',
    slug: 'gwangalli-drone-show',
    name_ko: '광안리 드론라이트쇼',
    name_zh: '廣安里無人機表演',
    name_en: 'Gwangalli Drone Light Show',
    type: 'activity',
    description: '廣安里海灘每週六晚間的無人機燈光秀，數百台無人機在廣安大橋前的夜空中組成各種圖案，搭配音樂與燈光效果，是釜山夜間最浪漫的免費表演。',
    address_ko: '부산 수영구 광안해변로 219',
    address_zh: '釜山水營區廣安海邊路219號（廣安里海灘）',
    district: '海雲台',
    city: '釜山',
    lat: 35.1533,
    lng: 129.1186,
    image_url: 'https://images.unsplash.com/photo-1473968512647-3e447244af8f?w=800&q=80',
    price_range: 'free',
    ticket_price_free: true,
    time_needed_minutes: 30,
    best_time_to_visit: '週六晚上 20:00（表演時間依季節調整，出發前確認）',
    kid_friendly_score: 5,
    kid_friendly_notes: '免費露天表演，小孩看到無人機燈光秀會超興奮。海灘旁觀看，氣氛浪漫。',
    min_age: 0,
    review_summary: {
      pros: ['免費觀看，超值享受', '無人機圖案精彩，小孩超興奮', '廣安大橋夜景搭配燈光秀超美'],
      cons: ['僅週六演出（需確認是否加場）', '下雨或風大取消', '人潮眾多，建議提早佔位'],
    },
    opening_hours: { sat: '20:00-20:15', note: '僅週六晚間，約15-20分鐘。時間依季節調整，出發前請上官網確認' },
    tips: [
      '4/4 是週六，正好是固定演出日',
      '建議提早30分鐘到海灘佔好位置',
      '從海雲台搭計程車約15分鐘',
      '看完後可在廣安里海灘旁吃晚餐',
    ],
    tags: ['無人機', '夜景', '免費', '廣安里', '海雲台', '表演'],
    rating: 4.7,
    review_count: 4500,
  },

  {
    id: 'c2',
    slug: 'oncheoncheon-cafe-street',
    name_ko: '온천천 카페거리',
    name_zh: '溫泉川咖啡廳街',
    name_en: 'Oncheoncheon Cafe Street',
    type: 'cafe',
    description: '溫泉川沿岸的人氣咖啡廳聚落，沿著小河散步，兩旁有各式風格咖啡廳和甜點店。河邊櫻花季時更美，適合悠閒地喝杯咖啡休息。',
    address_ko: '부산 동래구 온천천 카페거리 일대',
    address_zh: '釜山東萊區溫泉川咖啡廳街一帶',
    district: '海雲台',
    city: '釜山',
    lat: 35.1910,
    lng: 129.0780,
    image_url: 'https://images.unsplash.com/photo-1445116572660-236099ec97a0?w=800&q=80',
    price_range: 'moderate',
    avg_price_krw: 7000,
    spice_level: 'none',
    cuisine_type: ['咖啡', '甜點', '브런치'],
    kid_friendly_score: 4,
    kid_friendly_notes: '河邊散步適合帶小孩，多家咖啡廳有戶外座位。部分店家有兒童飲品和甜點。',
    has_english_menu: false,
    accepts_card: true,
    reservation_required: false,
    time_needed_minutes: 60,
    review_summary: {
      pros: ['河邊散步氛圍好', '咖啡廳選擇多', '4月有櫻花超美', '適合帶小孩悠閒走走'],
      cons: ['假日人潮多', '停車不便', '各店品質不一'],
    },
    opening_hours: { note: '各店營業時間不同，多數 10:00-21:00' },
    tips: ['沿著溫泉川散步選一家喜歡的坐下來', '4月初河邊櫻花也很美'],
    tags: ['咖啡廳', '散步', '櫻花', '溫泉川', '休閒'],
    rating: 4.4,
    review_count: 1800,
  },
]

// ══════════════════════════════════════════════════════════
// 輔助資料
// ══════════════════════════════════════════════════════════

export const typeLabels: Record<string, string> = {
  restaurant: '餐廳',
  cafe: '咖啡廳',
  dessert: '甜點/小吃',
  attraction: '景點',
  park: '公園',
  shopping: '購物/票券',
  activity: '活動',
}

export const spiceLevelLabels: Record<string, string> = {
  none: '完全無辣 ✅',
  mild: '微辣（可調整）⚠️',
  moderate: '中辣 🌶',
  spicy: '辣 🌶🌶',
}

export const priceLabels: Record<string, string> = {
  free: '免費',
  budget: '便宜 (₩10,000以下)',
  moderate: '中等 (₩10,000–30,000)',
  expensive: '高價 (₩30,000+)',
  luxury: '奢華',
}

export const districts = [
  { id: 'all', name: '全部' },
  { id: '海雲台', name: '海雲台' },
  { id: '西釜山', name: '西釜山' },
  { id: '影島', name: '影島' },
  { id: '機張', name: '機張' },
  { id: '全釜山', name: '全釜山' },
]

export const filterTypes = [
  { id: 'all', label: '全部' },
  { id: 'restaurant', label: '🍽 餐廳' },
  { id: 'dessert', label: '🍰 甜點/小吃' },
  { id: 'attraction', label: '🎡 景點' },
  { id: 'shopping', label: '🛍 購物/票券' },
]

// ══════════════════════════════════════════════════════════
// 行程模板
// ══════════════════════════════════════════════════════════

export const suggestedItineraries: SuggestedItinerary[] = [
  {
    id: 'busan-6days-personal',
    title: '釜山6天5夜家族旅行',
    days: 6,
    description: '4/1-4/6 釜山全覽：甘川洞韓服、松島纜車、大渚賞櫻、Luge遛遛車、膠囊列車、廣安里無人機、水族館，Day2&3包車',
    image_url: 'https://images.unsplash.com/photo-1519984388953-d2406bc725e1?w=600&q=80',
    spotIds: ['act1', 'act8', 'r7', 'act2', 'act4', 'c1', 'r8', 'p1', 'c2', 'act5', 'a4', 'k2', 'a3', 'act6', 'act7', 'a1', 's1'],
    schedule: [
      {
        day: 1, title: 'Day 1（4/1）抵達釜山・海雲台逛逛',
        items: [],
      },
      {
        day: 2, title: 'Day 2（4/2）包車：甘川洞→松島→影島→海雲台',
        items: [
          { spotId: 'act1', start: '09:30', duration: 90, note: '甘川洞韓服體驗（衣裳貸與），穿韓服逛彩色村落拍照' },
          { spotId: 'act8', start: '11:00', duration: 30, note: 'Flipbook Studio，穿韓服拍翻頁動畫書紀念' },
          { spotId: 'r7', start: '12:00', duration: 75, note: '明星一隻雞，整隻雞湯鍋午餐' },
          { spotId: 'act2', start: '13:30', duration: 60, note: '松島海上纜車，俯瞰松島海灣' },
          { spotId: 'act4', start: '15:00', duration: 90, note: 'ARTE MUSEUM 沉浸式數位藝術，光影超夢幻' },
          { spotId: 'c1', start: '16:30', duration: 45, note: 'P.ark 咖啡廳，還有時間的話去喝杯咖啡休息' },
          { spotId: 'r8', start: '18:30', duration: 75, note: '海雲台31cm海鮮刀削麵，包車回海雲台後晚餐' },
        ],
      },
      {
        day: 3, title: 'Day 3（4/3）包車：大渚賞櫻→溫泉川→Luge→樂天',
        items: [
          { spotId: 'p1', start: '09:30', duration: 120, note: '大渚生態公園賞櫻騎車，4月初櫻花滿開' },
          { spotId: 'c2', start: '11:30', duration: 60, note: '溫泉川咖啡廳街，河邊散步選間咖啡廳休息' },
          { spotId: 'act5', start: '14:00', duration: 90, note: 'Skyline Luge 遛遛車，小孩超愛！建議買多次票。午餐可在附近解決' },
          { spotId: 'k2', start: '16:00', duration: 180, note: '樂天 Premium Outlet 逛街（或改去樂天世界樂園 a4）。晚餐待定' },
        ],
      },
      {
        day: 4, title: 'Day 4（4/4）膠囊列車→海灘→廣安里',
        items: [
          { spotId: 'a3', start: '09:30', duration: 90, note: '藍線公園天空膠囊列車，沿海岸欣賞海景' },
          { spotId: 'act6', start: '11:30', duration: 40, note: '青沙浦天空步道，免費透明玻璃步道（視天氣決定）' },
          { spotId: 'act7', start: '20:00', duration: 30, note: '廣安里無人機表演（週六固定演出）。下午可在海灘玩沙或搭遊艇' },
        ],
      },
      {
        day: 5, title: 'Day 5（4/5）水族館→海灘→新世界百貨',
        items: [
          { spotId: 'a1', start: '10:00', duration: 120, note: 'SEA LIFE 水族館，3歲以下免費，提前網購省30%' },
          { spotId: 's1', start: '15:00', duration: 180, note: '新世界百貨 Centum City 逛街，B1外國旅客服務台領折扣券。中間可在海雲台海灘玩沙' },
        ],
      },
      {
        day: 6, title: 'Day 6（4/6）回家',
        items: [],
      },
    ],
  },
  {
    id: 'busan-kids-day',
    title: '釜山親子一日精華',
    days: 1,
    description: '適合2-6歲小孩的一天行程：水族館→海灘小火車→親子晚餐，全程無辣',
    image_url: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=600&q=80',
    spotIds: ['a1', 'a3', 'r6'],
    schedule: [
      {
        day: 1, title: '親子完整一天',
        items: [
          { spotId: 'a1', start: '10:00', duration: 120, note: 'SEA LIFE水族館，3歲以下免費，提前網購省30%' },
          { spotId: 'a3', start: '13:30', duration: 90, note: '藍線公園海灘小火車，沿海岸欣賞東海海景' },
          { spotId: 'r6', start: '18:00', duration: 90, note: '맛찬들鹽烤豬肉海雲台店，完全無辣，小孩最愛' },
        ],
      },
    ],
  },
  {
    id: 'busan-kids-park-tour',
    title: '釜山親子景點巡禮',
    days: 2,
    description: '兩天玩遍釜山最棒的親子景點，2-6歲必訪',
    image_url: 'https://images.unsplash.com/photo-1575783970733-1aaedde1db74?w=600&q=80',
    spotIds: ['a3', 'g1', 'a2', 'r6'],
    schedule: [
      {
        day: 1, title: '藍線公園＋豬肉湯飯',
        items: [
          { spotId: 'a3', start: '09:30', duration: 90, note: '藍線公園海灘小火車，帶幼兒首選' },
          { spotId: 'g1', start: '12:00', duration: 60, note: '密陽純大豬肉湯飯，24H營業，幼兒清湯無辣' },
        ],
      },
      {
        day: 2, title: '海洋博物館＋親子晚餐',
        items: [
          { spotId: 'a2', start: '10:00', duration: 150, note: '國立海洋博物館，完全免費！幼兒互動區' },
          { spotId: 'r6', start: '18:30', duration: 90, note: '맛찬들鹽烤豬肉海雲台店收尾' },
        ],
      },
    ],
  },
]
