import { Spot } from './types'

export const spots: Spot[] = [
  // ── 首爾 弘大 ──────────────────────────────────────────────────────────
  {
    id: '1',
    slug: 'mangwon-market',
    name_ko: '망원시장',
    name_zh: '望遠市場',
    name_en: 'Mangwon Market',
    type: 'attraction',
    description: '首爾最有生活感的傳統市場，鄰近弘大，是當地人日常採買的地方，也是網紅打卡熱點。必吃炸雞、魚板、年糕等街頭小吃。',
    address_ko: '서울 마포구 포은로 6',
    address_zh: '首爾麻浦區浦隱路6號',
    district: '弘大/望遠',
    city: '首爾',
    lat: 37.5565,
    lng: 126.9022,
    image_url: 'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=800&q=80',
    price_range: 'budget',
    avg_price_krw: 5000,
    ticket_price_free: true,
    time_needed_minutes: 90,
    best_time_to_visit: '上午10點–下午2點（最熱鬧）',
    tips: [
      '週一公休，請注意',
      '帶現金，部分攤販不收卡',
      '推薦先去二樓熟食區吃早午餐再逛',
      '地鐵6號線望遠站2號出口步行5分鐘',
    ],
    tags: ['傳統市場', '街頭小吃', '弘大周邊', '免費'],
    opening_hours: { tue: '08:00-21:00', wed: '08:00-21:00', thu: '08:00-21:00', fri: '08:00-21:00', sat: '08:00-21:00', sun: '08:00-21:00', note: '週一公休' },
    youtube_sources: [
      { url: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ', title: '首爾必去傳統市場！望遠市場完整攻略', creator: '韓國旅遊日記', thumbnail: 'https://i.ytimg.com/vi/dQw4w9WgXcQ/hqdefault.jpg' }
    ],
  },
  {
    id: '2',
    slug: 'yeonnam-dong',
    name_ko: '연남동',
    name_zh: '延南洞',
    name_en: 'Yeonnam-dong',
    type: 'attraction',
    description: '被稱為「首爾的上海」，充滿個性咖啡廳、小餐館與藝術空間。弘大旁的靜謐街區，適合漫步探索。',
    address_ko: '서울 마포구 연남동',
    address_zh: '首爾麻浦區延南洞',
    district: '弘大/延南洞',
    city: '首爾',
    lat: 37.5613,
    lng: 126.9259,
    image_url: 'https://images.unsplash.com/photo-1601042879364-f3947d3f9c16?w=800&q=80',
    price_range: 'moderate',
    ticket_price_free: true,
    time_needed_minutes: 120,
    best_time_to_visit: '下午2點–傍晚6點',
    tips: [
      '京義線林蔭道（경의선 숲길）是拍照必去點',
      '假日人潮很多，建議平日前往',
      '弘大地鐵站3號出口步行10分鐘',
    ],
    tags: ['散步', '咖啡廳', '打卡', '弘大周邊'],
    opening_hours: { note: '全天開放的街區' },
  },
  {
    id: '3',
    slug: 'mapo-fried-chicken',
    name_ko: '마포 통닭',
    name_zh: '麻浦整隻炸雞',
    name_en: 'Mapo Tongdak',
    type: 'restaurant',
    cuisine_type: ['韓式', '炸雞'],
    description: '望遠市場內最知名的老字號炸雞攤，整隻現炸、皮酥肉嫩，是YouTuber必推的庶民美食。',
    address_ko: '서울 마포구 포은로 6 망원시장 내',
    address_zh: '首爾麻浦區浦隱路6號 望遠市場內',
    district: '弘大/望遠',
    city: '首爾',
    lat: 37.5566,
    lng: 126.9024,
    image_url: 'https://images.unsplash.com/photo-1562802378-063ec186a863?w=800&q=80',
    price_range: 'budget',
    avg_price_krw: 13000,
    has_english_menu: false,
    accepts_card: false,
    reservation_required: false,
    recommended_dishes: [
      { name_ko: '통닭', name_zh: '整隻炸雞', price_krw: 13000, description: '招牌整隻現炸，皮薄酥脆，份量大一人也吃得完', must_order: true },
      { name_ko: '닭똥집', name_zh: '炸雞腎', price_krw: 5000, description: '脆嫩的雞胗，是必點下酒小吃', must_order: false },
    ],
    ordering_tips: [
      '完全不懂韓文沒關係，直接指攤位上的整隻雞比手畫腳即可',
      '現金支付，一隻約13,000韓元（約台幣300元）',
      '現點現炸，約等10分鐘',
      '可以說「하나 주세요（하나 주세요）」= 給我一個',
    ],
    opening_hours: { tue: '10:00-19:00', wed: '10:00-19:00', thu: '10:00-19:00', fri: '10:00-19:00', sat: '10:00-19:00', sun: '10:00-19:00', note: '週一公休，售完為止' },
    tags: ['炸雞', '傳統市場', '必吃', '便宜', '弘大'],
    tips: ['排隊很正常，耐心等候', '帶現金！'],
    rating: 4.8,
    review_count: 1240,
  },

  // ── 首爾 明洞 ──────────────────────────────────────────────────────────
  {
    id: '4',
    slug: 'myeongdong-street-food',
    name_ko: '명동 길거리 음식',
    name_zh: '明洞街頭小吃',
    name_en: 'Myeongdong Street Food',
    type: 'attraction',
    description: '首爾最熱門的購物街，傍晚起攤販林立，必試雞蛋麵包、起司龍蝦、螃蟹、串烤等各式小吃，是韓國美食最密集的區域之一。',
    address_ko: '서울 중구 명동길',
    address_zh: '首爾中區明洞街',
    district: '明洞',
    city: '首爾',
    lat: 37.5636,
    lng: 126.9864,
    image_url: 'https://images.unsplash.com/photo-1546619900-31e7a5cff2e1?w=800&q=80',
    price_range: 'budget',
    avg_price_krw: 8000,
    ticket_price_free: true,
    time_needed_minutes: 120,
    best_time_to_visit: '傍晚5點後（攤販全開）',
    tips: [
      '地鐵4號線明洞站8號出口直達',
      '雞蛋麵包（계란빵）約2,000韓元，超值必吃',
      '起司龍蝦（랍스터 치즈구이）約15,000韓元，網紅必拍',
      '螃蟹串（게 꼬치）約10,000韓元，現點現做',
      '傍晚後更多攤販出現，夜晚最熱鬧',
    ],
    tags: ['街頭小吃', '購物', '明洞', '必去', '夜晚'],
    opening_hours: { note: '攤販傍晚17:00後陸續開始，22:00前大多收攤' },
  },
  {
    id: '5',
    slug: 'lotteria-myeongdong',
    name_ko: '을지면옥',
    name_zh: '乙支麵屋',
    name_en: 'Euljimyeonok',
    type: 'restaurant',
    cuisine_type: ['韓式', '冷麵', '平壤冷麵'],
    description: '1985年開業的平壤冷麵老店，是首爾最著名的冷麵名店之一，許多韓國藝人和政商名流的愛店。清爽牛骨湯底，麵條Q彈。',
    address_ko: '서울 중구 을지로 59',
    address_zh: '首爾中區乙支路59號',
    district: '明洞/乙支路',
    city: '首爾',
    lat: 37.5656,
    lng: 126.9869,
    image_url: 'https://images.unsplash.com/photo-1569050467447-ce54b3bbc37d?w=800&q=80',
    price_range: 'moderate',
    avg_price_krw: 15000,
    has_english_menu: true,
    accepts_card: true,
    reservation_required: false,
    recommended_dishes: [
      { name_ko: '평양냉면', name_zh: '平壤冷麵', price_krw: 15000, description: '招牌菜，清爽牛骨高湯，略帶甜味，第一次吃可能不習慣但越吃越愛', must_order: true, image_url: 'https://images.unsplash.com/photo-1569050467447-ce54b3bbc37d?w=400&q=80' },
      { name_ko: '수육', name_zh: '白切肉', price_krw: 30000, description: '嫩煮豬肉切片，沾醬吃，搭冷麵絕配', must_order: true },
      { name_ko: '만두', name_zh: '水餃', price_krw: 10000, description: '手工水餃，皮薄餡實', must_order: false },
    ],
    ordering_tips: [
      '排隊很正常，尤其午餐時段，可能等30分鐘以上',
      '冷麵上桌前服務員會先問「요기서 자르실래요?」意思是「要幫你剪麵嗎？」→ 說「네（ne）」就是要，「괜찮아요（gwaenchana-yo）」就是不用',
      '湯可以免費續加，說「국물 더 주세요（gungmul deo juseyo）」',
      '初次嘗試平壤冷麵：湯底偏淡，可加醋和芥末調味',
    ],
    opening_hours: { mon: '11:30-21:00', tue: '11:30-21:00', wed: '11:30-21:00', thu: '11:30-21:00', fri: '11:30-21:00', sat: '11:30-21:00', note: '週日公休，賣完就關' },
    tags: ['冷麵', '老店', '必吃', '午餐', '明洞'],
    tips: ['帶現金備用', '避開12-13點尖峰'],
    rating: 4.7,
    review_count: 3200,
  },

  // ── 首爾 景福宮/北村 ──────────────────────────────────────────────────
  {
    id: '6',
    slug: 'gyeongbokgung',
    name_ko: '경복궁',
    name_zh: '景福宮',
    name_en: 'Gyeongbokgung Palace',
    type: 'attraction',
    description: '朝鮮王朝最大的宮殿，建於1395年，是首爾最重要的歷史地標。每天上午10點和下午2點有盛大的守門將交接儀式，穿韓服免費入場！',
    address_ko: '서울 종로구 사직로 161',
    address_zh: '首爾鐘路區社稷路161號',
    district: '景福宮/北村',
    city: '首爾',
    lat: 37.5796,
    lng: 126.9770,
    image_url: 'https://images.unsplash.com/photo-1548115184-bc6544d06a58?w=800&q=80',
    price_range: 'budget',
    ticket_price_krw: 3000,
    ticket_price_free: false,
    booking_url: 'https://www.royalpalace.go.kr',
    time_needed_minutes: 150,
    best_time_to_visit: '早上9點半開門前到，避開人潮；或下午4點後光線美適合拍照',
    tips: [
      '穿韓服可免費入場！附近有很多韓服出租，約20,000-30,000韓元',
      '週二公休',
      '守門將交接儀式：上午10點、下午2點，每次30分鐘，免費觀看',
      '地鐵3號線景福宮站5號出口直達',
      '國立民俗博物館在宮內，免費參觀',
      '旁邊的北村韓屋村步行可達，建議一起安排',
    ],
    tags: ['歷史', '宮殿', '韓服', '必去', '景福宮'],
    opening_hours: {
      mon: '09:00-18:00', wed: '09:00-18:00', thu: '09:00-18:00', fri: '09:00-18:00', sat: '09:00-18:00', sun: '09:00-18:00',
      note: '週二公休；夏季(6-8月)延長至19:00；冬季(11-1月)至17:00',
    },
    rating: 4.8,
    review_count: 15000,
  },
  {
    id: '7',
    slug: 'tosokchon-samgyetang',
    name_ko: '토속촌 삼계탕',
    name_zh: '土俗村蔘雞湯',
    name_en: 'Tosokchon Samgyetang',
    type: 'restaurant',
    cuisine_type: ['韓式', '蔘雞湯', '補品'],
    description: '景福宮旁最著名的蔘雞湯名店，已有30多年歷史，每天排隊到店外。整隻嫩雞塞入糯米、人蔘、栗子，湯頭濃郁鮮甜。',
    address_ko: '서울 종로구 자하문로5길 5',
    address_zh: '首爾鐘路區紫霞門路5巷5號',
    district: '景福宮',
    city: '首爾',
    lat: 37.5805,
    lng: 126.9712,
    image_url: 'https://images.unsplash.com/photo-1583394293214-ce4e4e7a2a90?w=800&q=80',
    price_range: 'moderate',
    avg_price_krw: 20000,
    has_english_menu: true,
    accepts_card: true,
    reservation_required: false,
    recommended_dishes: [
      { name_ko: '삼계탕', name_zh: '蔘雞湯', price_krw: 20000, description: '招牌！整隻小雞燉煮，內填糯米人蔘，湯頭清甜補身，是首爾最正宗的版本', must_order: true, image_url: 'https://images.unsplash.com/photo-1583394293214-ce4e4e7a2a90?w=400&q=80' },
      { name_ko: '옻닭', name_zh: '漆樹雞湯', price_krw: 22000, description: '加入漆樹熬煮，味道更深層，適合喜歡中藥風味的人', must_order: false },
    ],
    ordering_tips: [
      '開門前15-20分鐘到，通常已有排隊人潮',
      '一人一碗剛好，不需加點',
      '附有泡菜、小菜免費無限取用',
      '雞骨頭可以請服務員拿走，不用自己處理',
      '吃完可以加飯（공기밥）進湯裡，約1,000韓元',
      '人蔘酒（인삼주）免費提供一小杯，可以拒絕',
    ],
    opening_hours: { mon: '10:00-22:00', tue: '10:00-22:00', wed: '10:00-22:00', thu: '10:00-22:00', fri: '10:00-22:00', sat: '10:00-22:00', sun: '10:00-22:00', note: '全年無休，但排隊等候可能需要30-60分鐘' },
    tags: ['蔘雞湯', '老店', '必吃', '景福宮', '補品'],
    tips: ['早點去或避開12-14點', '景福宮遊覽後順道來吃午餐是經典行程'],
    rating: 4.6,
    review_count: 8900,
    youtube_sources: [
      { url: 'https://www.youtube.com/watch?v=abc123', title: '首爾必吃蔘雞湯！土俗村排隊值得嗎？', creator: 'Mark Wiens', thumbnail: '' }
    ],
  },

  // ── 首爾 弘大 餐廳 ──────────────────────────────────────────────────────
  {
    id: '8',
    slug: 'hongdae-gopchang',
    name_ko: '홍대 곱창골목',
    name_zh: '弘大烤腸巷',
    name_en: 'Hongdae Gopchang Alley',
    type: 'restaurant',
    cuisine_type: ['韓式', '烤肉', '烤腸'],
    description: '弘大著名的烤腸街，多家店並排，夜晚燈火通明，是韓國人最愛的深夜宵夜選擇。腸子處理乾淨無異味，搭配韓式燒酒是標配。',
    address_ko: '서울 마포구 홍익로6길 일대',
    address_zh: '首爾麻浦區弘益路6巷一帶',
    district: '弘大',
    city: '首爾',
    lat: 37.5542,
    lng: 126.9245,
    image_url: 'https://images.unsplash.com/photo-1529692236671-f1f6cf9683ba?w=800&q=80',
    price_range: 'moderate',
    avg_price_krw: 25000,
    has_english_menu: false,
    accepts_card: true,
    reservation_required: false,
    recommended_dishes: [
      { name_ko: '곱창', name_zh: '烤小腸', price_krw: 15000, description: '小腸烤得焦脆，沾醬吃，是最傳統的點法', must_order: true },
      { name_ko: '막창', name_zh: '烤大腸', price_krw: 16000, description: '大腸口感更豐富，脂肪多，重口味必點', must_order: true },
      { name_ko: '볶음밥', name_zh: '收尾炒飯', price_krw: 3000, description: '烤完腸子後，用鍋裡的油脂炒飯，是精華！', must_order: true },
    ],
    ordering_tips: [
      '指著菜單上的圖片點餐即可，說「이거 주세요（igeo juseyo）」= 給我這個',
      '烤腸通常由店員幫你烤，不需要自己動手',
      '最後一定要點炒飯（볶음밥）！說「볶음밥 주세요」',
      '配燒酒（소주）或生啤（생맥주）是標配',
      '一人份約15,000-16,000韓元，通常2人份起跳',
    ],
    opening_hours: { mon: '17:00-02:00', tue: '17:00-02:00', wed: '17:00-02:00', thu: '17:00-02:00', fri: '17:00-03:00', sat: '17:00-03:00', sun: '17:00-02:00' },
    tags: ['烤腸', '宵夜', '弘大', '燒酒', '深夜'],
    tips: ['晚上8點後人最多，建議6點去卡位'],
    rating: 4.5,
    review_count: 2300,
  },

  // ── 釜山 ──────────────────────────────────────────────────────────────
  {
    id: '9',
    slug: 'gamcheon-village',
    name_ko: '감천문화마을',
    name_zh: '甘川文化村',
    name_en: 'Gamcheon Culture Village',
    type: 'attraction',
    description: '被稱為「韓國的馬丘比丘」，彩色房屋層疊在山坡上，是釜山最具代表性的景點。走在巷弄間有各種藝術裝置，別有風情。',
    address_ko: '부산 사하구 감내2로 203',
    address_zh: '釜山沙下區甘內2路203號',
    district: '甘川洞',
    city: '釜山',
    lat: 35.0979,
    lng: 129.0104,
    image_url: 'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=800&q=80',
    price_range: 'budget',
    ticket_price_krw: 2000,
    ticket_price_free: false,
    time_needed_minutes: 120,
    best_time_to_visit: '早上9-11點或傍晚4-6點，避開正午烈日',
    tips: [
      '門票2,000韓元，可兌換成村內消費（明信片或小吃）',
      '坡度陡，穿舒適的運動鞋',
      '從釜山地鐵1號線土城站前搭乙席巴士（마을버스 사하구 2-2）直達',
      '準備好地圖（入口處有免費）',
      '小王子裝置藝術是必拍點',
    ],
    tags: ['打卡', '藝術', '彩色村落', '釜山', '必去'],
    opening_hours: { mon: '09:00-18:00', tue: '09:00-18:00', wed: '09:00-18:00', thu: '09:00-18:00', fri: '09:00-18:00', sat: '09:00-18:00', sun: '09:00-18:00' },
    rating: 4.5,
    review_count: 9800,
  },
  {
    id: '10',
    slug: 'busan-milmyeon',
    name_ko: '부산 밀면',
    name_zh: '釜山小麥冷麵',
    name_en: 'Busan Milmyeon',
    type: 'restaurant',
    cuisine_type: ['韓式', '冷麵', '釜山料理'],
    description: '密麵（밀면）是釜山獨有的冷麵，使用小麥麵條而非蕎麥，是韓戰後避難至釜山的居民創造的美食。當地人的日常午餐首選。',
    address_ko: '부산 부산진구 가야대로784번길 8',
    address_zh: '釜山釜山鎮區伽倻大路784巷8號',
    district: '西面/甘天',
    city: '釜山',
    lat: 35.1531,
    lng: 129.0553,
    image_url: 'https://images.unsplash.com/photo-1569050467447-ce54b3bbc37d?w=800&q=80',
    price_range: 'budget',
    avg_price_krw: 9000,
    has_english_menu: false,
    accepts_card: true,
    reservation_required: false,
    recommended_dishes: [
      { name_ko: '물밀면', name_zh: '湯冷麵', price_krw: 9000, description: '清爽牛骨湯底，麵條有嚼勁，加辣醬混拌更好吃', must_order: true },
      { name_ko: '비빔밀면', name_zh: '拌冷麵', price_krw: 9000, description: '辣醬拌冷麵，爽辣開胃，釜山人最愛', must_order: true },
      { name_ko: '만두', name_zh: '水餃', price_krw: 5000, description: '當地口味的手工水餃，加點很值得', must_order: false },
    ],
    ordering_tips: [
      '兩種版本：湯的（물밀면 / mul-milmyeon）或辣拌的（비빔밀면 / bibim-milmyeon）',
      '不辣的說「안 맵게 주세요（an maepge juseyo）」',
      '加醋（식초）和芥末（겨자）可以自己加，桌上都有',
    ],
    opening_hours: { mon: '10:00-21:00', tue: '10:00-21:00', wed: '10:00-21:00', thu: '10:00-21:00', fri: '10:00-21:00', sat: '10:00-21:00', sun: '10:00-20:00' },
    tags: ['冷麵', '釜山', '在地美食', '便宜', '午餐'],
    rating: 4.4,
    review_count: 1800,
  },

  // ── 全羅南道 / 濟州島 ─────────────────────────────────────────────────
  {
    id: '11',
    slug: 'jeju-hallasan',
    name_ko: '한라산',
    name_zh: '漢拏山',
    name_en: 'Hallasan Mountain',
    type: 'activity',
    description: '韓國最高峰（1,950公尺），也是濟州島的象徵。健行路線多條，觀音寺路線最受歡迎，可看到火山口湖（白鹿潭）。',
    address_ko: '제주 서귀포시 토평동 산15-1',
    address_zh: '濟州特別自治道西歸浦市土坪洞山15-1',
    district: '漢拏山',
    city: '濟州',
    lat: 33.3617,
    lng: 126.5292,
    image_url: 'https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?w=800&q=80',
    price_range: 'budget',
    ticket_price_free: true,
    time_needed_minutes: 480,
    best_time_to_visit: '春（4-5月）賞鐵線蓮；秋（10-11月）楓葉；夏季避開午後雷陣雨',
    tips: [
      '完全免費入場',
      '需提前網路預約（部分路線）',
      '入山截止時間請看官網，務必在指定時間前下山',
      '帶足飲水和食物，山上無補給',
      '成允岳路線最容易（4小時來回），觀音寺路線最壯觀但最難（6-8小時）',
      '山頂可能有雲，出發前查看天氣預報',
    ],
    tags: ['健行', '自然', '濟州', '免費', '漢拏山'],
    opening_hours: { note: '依季節和路線不同，詳見官網 https://www.hallasan.go.kr' },
    rating: 4.7,
    review_count: 5200,
  },

  // ── 韓國通用 必吃小吃 ─────────────────────────────────────────────────
  {
    id: '12',
    slug: 'korea-bingsu',
    name_ko: '빙수 전문점',
    name_zh: '韓式刨冰名店',
    name_en: 'Korean Bingsu',
    type: 'cafe',
    cuisine_type: ['甜點', '刨冰', '韓式甜品'],
    description: '韓式刨冰（빙수）是夏季必吃，以牛奶冰為基底，加上紅豆、年糕、水果等配料，與台式刨冰截然不同的細緻綿密口感。',
    address_ko: '서울 전역',
    address_zh: '首爾各地均有',
    district: '全首爾',
    city: '首爾',
    lat: 37.5665,
    lng: 126.9780,
    image_url: 'https://images.unsplash.com/photo-1563805042-7684c019e1cb?w=800&q=80',
    price_range: 'moderate',
    avg_price_krw: 15000,
    recommended_dishes: [
      { name_ko: '팥빙수', name_zh: '紅豆刨冰', price_krw: 13000, description: '最經典款，滿滿紅豆餡加上牛奶冰，必試', must_order: true },
      { name_ko: '망고빙수', name_zh: '芒果刨冰', price_krw: 16000, description: '新鮮芒果果肉，酸甜清爽，適合夏天', must_order: false },
      { name_ko: '딸기빙수', name_zh: '草莓刨冰', price_krw: 17000, description: '草莓季（冬春）限定，甜美必吃', must_order: false },
    ],
    ordering_tips: [
      '一碗份量很大，建議2人共享',
      '推薦名店：冰뚜루（빙뚜루）、雪冰（설빙）連鎖或獨立咖啡廳',
      '夏季（6-8月）是旺季，可能需要等候',
    ],
    tags: ['甜點', '刨冰', '夏季必吃', '網紅', '打卡'],
    opening_hours: { note: '各店不同，連鎖店約11:00-22:00' },
    rating: 4.6,
    review_count: 4500,
  },
]

export const districts = [
  { id: 'all', name: '全部地區' },
  { id: '弘大/望遠', name: '弘大・望遠', city: '首爾' },
  { id: '弘大/延南洞', name: '延南洞', city: '首爾' },
  { id: '明洞', name: '明洞', city: '首爾' },
  { id: '景福宮/北村', name: '景福宮・北村', city: '首爾' },
  { id: '弘大', name: '弘大', city: '首爾' },
  { id: '甘川洞', name: '甘川洞', city: '釜山' },
  { id: '西面/甘天', name: '西面', city: '釜山' },
  { id: '漢拏山', name: '漢拏山', city: '濟州' },
  { id: '全首爾', name: '全首爾' },
]

export const typeLabels: Record<string, string> = {
  restaurant: '餐廳',
  cafe: '咖啡廳',
  attraction: '景點',
  accommodation: '住宿',
  shopping: '購物',
  activity: '活動',
}

export const priceLabels: Record<string, string> = {
  budget: '便宜 (₩10,000以下)',
  moderate: '中等 (₩10,000–30,000)',
  expensive: '高價 (₩30,000–80,000)',
  luxury: '奢華 (₩80,000+)',
}

export const cities = ['全部', '首爾', '釜山', '濟州']

export const suggestedItineraries = [
  {
    id: 'seoul-3days',
    title: '首爾精華3天',
    days: 3,
    description: '涵蓋弘大、明洞、景福宮，兼顧美食與文化',
    image_url: 'https://images.unsplash.com/photo-1548115184-bc6544d06a58?w=600&q=80',
    spotIds: ['6', '7', '4', '5', '1', '3', '2', '8'],
    schedule: [
      {
        day: 1,
        title: '歷史文化日',
        items: [
          { spotId: '6', start: '09:00', duration: 150, note: '穿韓服免費入場！' },
          { spotId: '7', start: '12:00', duration: 60, note: '排隊名店，提早到' },
          { spotId: '5', start: '18:30', duration: 90, note: '平壤冷麵晚餐' },
          { spotId: '4', start: '20:00', duration: 90, note: '明洞逛街＋街頭小吃' },
        ],
      },
      {
        day: 2,
        title: '弘大潮流日',
        items: [
          { spotId: '1', start: '10:00', duration: 90, note: '逛市場吃早午餐' },
          { spotId: '3', start: '11:00', duration: 30, note: '市場內炸雞必吃' },
          { spotId: '2', start: '14:00', duration: 120, note: '延南洞散步咖啡廳' },
          { spotId: '8', start: '19:00', duration: 120, note: '弘大烤腸宵夜' },
        ],
      },
      {
        day: 3,
        title: '自由購物日',
        items: [
          { spotId: '4', start: '11:00', duration: 60, note: '明洞購物' },
          { spotId: '12', start: '14:00', duration: 60, note: '下午吃刨冰' },
        ],
      },
    ],
  },
  {
    id: 'busan-2days',
    title: '釜山週末2天',
    days: 2,
    description: '釜山精華：彩色村落、海雲台、在地美食',
    image_url: 'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=600&q=80',
    spotIds: ['9', '10'],
    schedule: [
      {
        day: 1,
        title: '釜山探索日',
        items: [
          { spotId: '9', start: '09:30', duration: 120, note: '甘川文化村，早去人少' },
          { spotId: '10', start: '12:30', duration: 60, note: '在地人的冷麵午餐' },
        ],
      },
    ],
  },
]
